laba2
HepoH3/MIET_FPGA_practicum pull request #26
Opened 2020-05-07 19:28 UTC by DOOMKEKER

2020-05-09 14:22 UTC, HepoH3 requested changes
1) Прямо выше сказано, что есть конфликты пулреквеста. См Readme в оригинальном репе.
2) В репе нет ничего, что нужно было бы удалять.
3) В репе дан прототип, который должен быть реализован. Если дан counter с такими-то портами, значит этот же модуль и должен быть реализован.

2020-05-09 14:22 UTC, HepoH3 commented on lab2/rtl/counter2.v
> +module counter2(
название модуля не должно меняться

2020-05-09 14:22 UTC, HepoH3 commented on lab2/rtl/counter2.v
> +//������� ������ �� ������� ������ ������ �������� 40, �� ����� ���� 79 ��� ����� 1, �� ������ � �� ������� ����� ��������)
битая кодировка

2020-05-09 14:22 UTC, HepoH3 commented on lab2/rtl/counter2.v
> +endcase
отступ для кейса, нормальный отступ для всего остального

2020-05-09 14:22 UTC, HepoH3 commented on lab2/rtl/counter2_tb.v
> +localparam CLK_SEMI = ( 1000 / CLK_FREQ_MHZ) / 2;
выровнять

2020-05-09 14:22 UTC, HepoH3 commented on lab2/rtl/counter2_tb.v
> +end
в кодстайле указано другое количество пробелов на табуляцию

2020-05-09 14:22 UTC, HepoH3 commented on lab2/rtl/main.v
> +end
зачем этот модуль вообще нужен? топовым модулем должен быть counter, кроме того, это не программирование, что еще за main?

2020-05-12 10:26 UTC, DOOMKEKER commented
Что-то я жестко напортачил :/ 
я не знаю как вернуть старый каунтер, так чтобы еще остаться на этом пул реквесте ¯\(о_О)/¯

2020-05-12 11:31 UTC, DOOMKEKER commented
Упс... Случайно запушил индивидуальные тоже ¯\(о_О)/¯
если все будет четко, то вот мои задания

![изображение](https://user-images.githubusercontent.com/25349258/81681811-27debe80-945d-11ea-9772-3625ff3939d2.png)

![изображение](https://user-images.githubusercontent.com/25349258/81681552-0382e200-945d-11ea-8815-7357a5c0aadb.png)

![изображение](https://user-images.githubusercontent.com/25349258/81681679-185f7580-945d-11ea-8e0f-d58bb3f58393.png)

2020-05-12 13:46 UTC, HepoH3 commented
> 
> 
> Что-то я жестко напортачил :/
> я не знаю как вернуть старый каунтер, так чтобы еще остаться на этом пул реквесте ¯(о_О)/¯

Старый — это от базовой части? Самый простой вариант, через историю коммитов скопировать содержимое вашего файла и заменить им текущий файл.

Для начала вам нужно спулить коммиты из апстрима, об этом написано в README оригинального репозитория.  
Индивидуальное задание в любом случае будет приниматься только после сданой базовой части, так что лучше сосредоточьтесь пока на ней.

2020-05-12 14:12 UTC, DOOMKEKER commented
Переделал

2020-05-12 14:28 UTC, HepoH3 commented
Так, отлично, во всяком случае конфликтов от пул-реквеста больше нет.  
В данный момент, дизайн, который описан в вашем файле counter нежизнеспособен.  
Обратите внимание, что активным уровнем у кнопок является ноль. Кроме того, по заданию ваш дизайн должен реагировать на нажатие кнопки, а не ее удержание. Таким образом, вас должен интересовать момент, когда key[0] переходит из состояния 1 в состояние 0.

Сначала сдайте базовую часть. После этого я приму пул-реквест, вы сможете запушить в эту же ветку коммит с индивидуальным заданием, и открыть новый пул-реквест под него.

2020-05-12 17:30 UTC, HepoH3 requested changes

2020-05-12 17:30 UTC, HepoH3 commented on lab2/rtl/counter.v
> +end
Не надо таких вот изобретательств, у вас достаточно ресурсов, чтобы сделать два блока с `case`. Тем более, велосипед этот в итоге не работает и то что должно идти в hex0 идет в hex1 и наоборот.

2020-05-12 18:23 UTC, DOOMKEKER commented on lab2/rtl/counter.v
> +end
Нууу, я подумал это будет нагромождением)
А мне это заменить или оставить, но поменять выходы?

2020-05-12 18:44 UTC, HepoH3 commented on lab2/rtl/counter.v
> +end
Замените, такое в целом не очень хорошо для реального дизайна. Клоки — довольно хрупкие штуки. И перед отправкой проверьте у себя, что все работает и ничего не перепутано.

2020-05-12 18:47 UTC, DOOMKEKER commented on lab2/rtl/counter.v
> +end
Окей, понял. Спасибо за разъяснение!

2020-05-12 19:21 UTC, DOOMKEKER commented
я всего лишь сделал отступы ;(
(сейчас поправлю)

2020-05-12 19:28 UTC, DOOMKEKER commented
Извиняюсь за эту череду комитов. Atom решил удалить лишние два пробела, а я этого не заметил :/

2020-05-13 07:27 UTC, HepoH3 commented
> 
> 
> Извиняюсь за эту череду комитов. Atom решил удалить лишние два пробела в модуле, из-за этого вылетала ошибка о конфликте :/

Странно, конфликтов быть не должно, если вы спулили с апстрима все. Атом удаляет лишние пробелы, потому что это хороший тон не оставлять лишние пробелы в документе. Данная фича отключается в настройках.

2020-05-13 07:36 UTC, HepoH3 requested changes
Как исправите данные проблемы, больше ошибок вроде не будет.

2020-05-13 07:36 UTC, HepoH3 commented on lab2/rtl/counter.v
> +      4'h9 : meh0 = 7'b0010000;
У вас одинаковые значения семисегментника для цифр 8 и 9.

2020-05-13 07:36 UTC, HepoH3 commented on lab2/rtl/counter.v
> +reg  [7:0] counter;
Не очень хорошо давать регистру имя такое же как и у модуля.

2020-05-13 08:02 UTC, HepoH3 approved these changes
Отлично, замечаний больше нет.

2020-05-13 08:02 UTC, merged