Lab_2
HepoH3/MIET_FPGA_practicum pull request #28
Opened 2020-05-07 19:51 UTC by Che100r

2020-05-09 14:41 UTC, HepoH3 requested changes
Для начала надо исправить замечания ниже. Поскольку модуль не соответствует прототипу, быстро проверить его я не могу.

2020-05-09 14:41 UTC, HepoH3 commented on lab2/rtl/main.v
> +  );
Модуль дан в файле counter.v. Там его и надо реализовывать и название его трогать не надо. Вы не на программировании, какой еще main?

2020-05-09 14:41 UTC, HepoH3 commented on lab2/rtl/main.v
> +  reg       counter_for_second_hex; //����� ��� ����, ����� ��� �������� ������������ �� hex_on[0] � hex_on[1]
Битая кодировка

2020-05-09 14:41 UTC, HepoH3 commented on lab2/rtl/main.v
> +endmodule
Данная реализация конечно допустима, но здесь имеет место дублирование кода, а это нехорошо. Лучше вынести в отдельный модуль, и подключить здесь инстанса этого модуля.

2020-05-09 14:41 UTC, HepoH3 commented on lab2/rtl/main.v
> +  );
Порты модуля должны быть такими же как в прототипе.

2020-05-09 17:52 UTC, HepoH3 commented
Данные коммиты все еще не закрывают все требования.

2020-05-09 18:01 UTC, Che100r commented
> "Данные коммиты все еще не закрывают все требования."

 Что это значит? Коммиты недостаточно расписаны? Или они вообще не правильно написаны?

2020-05-09 18:47 UTC, HepoH3 commented
> 
> 
> > "Данные коммиты все еще не закрывают все требования."
> 
> Что это значит? Коммиты недостаточно расписаны? Или они вообще не правильно написаны?

Нет, это значит, что сделано не все, что я просил. Произведены правки касательно оформления, но главным требованием было:
>
>
> "Модуль дан в файле counter.v. Там его и надо реализовывать и название его трогать не надо. Вы не на программировании, какой еще main?"
>
>
Это значит следующее. Ожидалось, что вы предоставите модуль counter, с описанными в исходном файле портами. Этот модуль будет браться проверочной системе и прогоняться через тесты. Доколе вы будете пушить модуль с каким-то своим именем (например тем же main) — этот модуль не подключится проверочной системой и следовательно не будет проверен.

2020-05-10 07:46 UTC, HepoH3 requested changes
В общем и целом, все очень даже неплохо, к оформлению претензий не осталось никаких. Мелкие правки непосредственно по дизайну и думаю, после новых коммитов этот пул-реквест примем.

2020-05-10 07:46 UTC, HepoH3 commented on lab2/rtl/counter.v
> +  always @( posedge clk100_i or posedge rstn_i )
Несмотря на наличие rstn_i среди входных сигналов, он в этой лабе не используется. В качестве ресета у вас используется key[1].

2020-05-10 07:46 UTC, HepoH3 commented on lab2/rtl/counter.v
> +  assign key    = ~btn_sync[2] & btn_sync[1];
Описанная вами схема реагирует на отжатие кнопки, а должна реагировать на ее нажатие. Обратите внимание, что активным уровнем кнопки является ноль, а не единица.

2020-05-10 07:46 UTC, HepoH3 commented on lab2/rtl/counter.v
> +  reg [7:0] counter;
Называть регистр тем же именем, что и модуль — плохая идея.

2020-05-10 10:50 UTC, HepoH3 approved these changes
Поздравляю с первым принятым пул-реквестом!

2020-05-10 10:51 UTC, merged