Add files via upload
HepoH3/MIET_FPGA_practicum pull request #30
Opened 2020-05-07 20:10 UTC by Lii-evd

2020-05-09 14:53 UTC, HepoH3 requested changes
Пока топовый модуль не будет соответствовать данному вам прототипу, я не смогу проверить его работоспособность.

2020-05-09 14:53 UTC, HepoH3 commented on hex.v
> +end
В кодстайле указан другой размер табуляции

2020-05-09 14:53 UTC, HepoH3 commented on hex.v
> +        default: out = 7'b1111111;
защищаться default-ом конечно хорошо, но проверьте, достижим ли он когда-либо.

2020-05-09 14:53 UTC, HepoH3 commented on main.v
> +    );
Модуль дан в файле counter.v. Там его и надо реализовывать и название его трогать не надо. Вы не на программировании, какой еще main?

2020-05-09 14:53 UTC, HepoH3 commented on main.v
> +endmodule
Не хватает переноса строки

2020-05-09 14:53 UTC, HepoH3 commented on main_tb.v
> +dev DUT (.CLK_i(CLK_i),.RST_i(RST_i),.KEY_i(KEY_i),.SW_i(SW_i),.LEDR_o(LEDR_o),.HEX_o(HEX_o),.HEX_on_o(HEX_on_o));
Каждый порт с новой строки, пожалуйста, поберегите чужие глаза.

2020-05-12 18:18 UTC, HepoH3 commented
Что-то странное с вашим дизайном, вы хорошо его проверяли? Смотрите, что выходит на моей времянке:  
![](https://puu.sh/FJyw1/a831bc8257.png)  
Сверху сигналы тестбенча, снизу -- вашего дизайна. На каждое изменение sw приходится нажатие на кнопку, и, как следствие, изменение семисегментника hex0. У вас же он изменяется крайне редко.

2020-05-13 07:41 UTC, HepoH3 requested changes
Теперь ваш дизайн реагирует на отжатие кнопки, а не ее нажатие.
Обратите внимание, что активным уровнем у кнопок является ноль. Кроме того, по заданию ваш дизайн должен реагировать на нажатие кнопки, а не ее удержание. Таким образом, вас должен интересовать момент, когда key[0] переходит из состояния 1 в состояние 0.

2020-05-13 11:39 UTC, HepoH3 requested changes

2020-05-13 11:39 UTC, HepoH3 commented on counter.v
> +    data    <=  10'b0;
Нет, в моем предыдущем замечании речь шла не о `negedge key[0]`. Регистры вашего дизайна должны работать от clk, а не от key[0].

2020-05-14 07:30 UTC, HepoH3 requested changes

2020-05-14 07:30 UTC, HepoH3 commented on counter.v
> +    always @( negedge press_1 or posedge button[0] ) begin
Не используйте `negedge` или `posedge` от любых своих свистелок. Сигналами срабатывания блока always должны быть клоки и асинхронный ресет, если вы описываете синхронную логику. Перечитайте разработку и разберитесь как можно понять что раньше сигнал был одним, а теперь стал другим без использования `...edge`.

2020-05-14 12:40 UTC, Lii-evd commented on counter.v
> +    always @( negedge press_1 or posedge button[0] ) begin
Я уже 7 раз переделываю лабу и не могу понять, что вы от меня хотите. Я перечитала разработку и в каждом примере изменение сигналов регистрируется по negedge или posedge. Если не использовать их для моих "свистелок", то работа устройства не будет соответствовать вашим требованиям. Так же, без привязки к "свистелкам" схема будет работать по блоку синхронизации, что увеличит промежуток времени между нажатием кнопки и записью в регистр.  Если же вообще не использовать negedge или posedge, то схема будет откликаться и на фронт и на срез, что противоречит самой сути работы регистра.

2020-05-14 12:40 UTC, HepoH3 approved these changes
Зачтено.

2020-05-14 12:50 UTC, HepoH3 commented on counter.v
> +    always @( negedge press_1 or posedge button[0] ) begin
Для записи в регистры используются клоки, а не какие-то левые внутренние сигналы. Ваш дизайн предлагал именно это. Нет никаких проблем с тем, чтобы дождаться следующего клока, от вас никто не требует мгновенной реакции устройства.

2020-05-14 12:50 UTC, merged