Vt21 korsuntseva
HepoH3/MIET_FPGA_practicum pull request #33
Opened 2020-05-07 20:23 UTC by krsnvir

2020-05-09 15:08 UTC, HepoH3 requested changes
1) В репозиторий добавляются только исходники. Никаких временных файлов вивадо, за исключением (в редких случая) файлов проекта быть не должно;
2) ![Код-стайл](http://82.179.184.185:82/doku.php?id=verilog_guideline) не соблюден;
3) В исходном репе не дано ничего, что нужно было бы удалять.
4) В исходном репе дан интерфейс, который должен соблюдаться. Раз в папке лежит файл counter.v с описанным внутри модулем и его портами — значит в этом же файле должна появиться реализация именно этого модуля. Потому что другой человек который будет ожидать увидеть именно такой модуль.
5) Коммиты должны быть ![наполнены смыслом](https://habr.com/ru/post/416887/), а не вот эта фигня, что я вижу выше.

Пока топовый модуль не будет соответствовать прототипу, я не смогу проверить его работоспособность.

2020-05-10 21:02 UTC, HepoH3 requested changes
Ваш код не компилируется. Проверьте порты модуля REG_TEN.

2020-05-11 08:52 UTC, HepoH3 requested changes
Помимо замечаний выше, верните удаленный вами файл `lab2.pdf`.

2020-05-11 08:52 UTC, HepoH3 commented on lab2/rtl/counter.v
> +  .sw_i       ( sw_i     [9:0] ),
Это не обязательно. Если вы хотите подключить всю шину целиком, разрядность можно не указывать.

2020-05-11 08:52 UTC, HepoH3 commented on lab2/rtl/decoder_hex.v
> +  end
Интересное, но необязательное решение. Достаточно сбросить счетчик в других частях вашего устройства, и тогда на хексах загорится ноль, что вполне достаточно, и даже более ожидаемо.

2020-05-11 08:52 UTC, HepoH3 commented on lab2/rtl/counter.v
> +  );
Здесь у вас тоже проблемы с подключением модуля, проверьте имена сигналов. Перед любыми своими коммитами вы должны проверять дизайн на то, что всё собирается и работает в соответствии с вашими собственными тестами.  
В дальнейшем, если публикуемый вами код не будет компилироваться начнутся снижения оценки.

2020-05-11 08:55 UTC, krsnvir commented on lab2/rtl/counter.v
> +  );
Да, заметила это, когда уже отправила, простите.

2020-05-11 08:58 UTC, HepoH3 commented on lab2/rtl/counter.v
> +  );
Дело не в том, что вот, вы заставили меня запускать тесты на несобирающемся коде, что я время потратил.  
Это просто культура разработки. А вдруг вышло бы так, что ваш пул-реквест внезапно приняли, и эту ветку влили в репозиторий, которым пользуется десять тысяч разработчиков, каждый из которых спулил бы ваши коммиты и у него все сломалось.

2020-05-11 09:38 UTC, krsnvir commented on lab2/rtl/decoder_hex.v
> +  end
Это можно так оставить?

2020-05-11 09:54 UTC, HepoH3 commented on lab2/rtl/decoder_hex.v
> +  end
Лучше все же убрать, эти индикаторы должны непрерывно работать.

2020-05-11 11:12 UTC, HepoH3 requested changes
Ваш дизайн неработоспособный. Попробуйте написать простенький тест для его проверки, он бы сразу вскрыл проблему.

2020-05-11 11:12 UTC, HepoH3 commented on lab2/rtl/decoder_hex.v
> +  case ( kod_i[3:0] )
Указывать разряды здесь не обязательно, раз вы используете всю шину.

2020-05-11 11:12 UTC, HepoH3 commented on lab2/rtl/counter.v
> +  always @( posedge clk100_i or negedge rstn_i ) begin
В качестве ресета вашего устройства используется сигнал key_i[1].

2020-05-11 11:12 UTC, HepoH3 commented on lab2/rtl/counter.v
> +  end
Вы здесь ничего не забыли?

2020-05-11 11:12 UTC, HepoH3 commented on lab2/rtl/counter.v
> +     sw_event <= 1'b0;
Блоки if и else должны быть обрамлены begin/end даже если внутри будет одна строка.

2020-05-11 11:12 UTC, HepoH3 commented on lab2/rtl/counter.v
> +         counter_i <= counter_i + 1;
См. комментарий выше.

2020-05-11 12:28 UTC, krsnvir commented
Вопрос. В исходнике не используется hex_on, как тогда быть? И hex1_о, hex0_o  передан не через reg.
![Снимок](https://user-images.githubusercontent.com/62858477/81561510-b47d7400-93ac-11ea-9337-c83a4cf6a7b0.PNG)

2020-05-11 13:02 UTC, HepoH3 commented
> 
> 
> Вопрос. В исходнике не используется hex_on, как тогда быть? И hex1_о, hex0_o передан не через reg.
> ![Снимок](https://user-images.githubusercontent.com/62858477/81561510-b47d7400-93ac-11ea-9337-c83a4cf6a7b0.PNG)

А что такое hex_on  и зачем оно нужно?  
Даже если hex0, hex1 не указаны в портах модуля в качестве регистра, вы можете создать внутри свои регистры, которые потом можете подсоединить к hex0, hex1 через операцию `assign`.

2020-05-11 16:39 UTC, HepoH3 requested changes

2020-05-11 16:39 UTC, HepoH3 commented on lab2/rtl/counter.v
> +end
Активным уровнем у кнопок является ноль. Кроме того, ваш дизайн должен реагировать на нажатие кнопки, а не ее удержание. Таким образом, счетчик должен инкрементироваться после того, как key[0] перешел из 1 в 0.

2020-05-11 17:28 UTC, krsnvir commented on lab2/rtl/counter.v
> +end
always @( posedge clk100_i or negedge key_i[1] ) begin 
if ( !key_i[1] ) begin 
counter_i <= {DATA_WIDTH{1'b0}}; 
end 
else 
if( negedge key_i[0] ) begin 
counter_i <= counter_i + 1; 
end 
end
Так будет правильно?

2020-05-11 18:06 UTC, HepoH3 commented on lab2/rtl/counter.v
> +end
> 
> 
> always @( posedge clk100_i or negedge key_i[1] ) begin
> if ( !key_i[1] ) begin
> counter_i <= {DATA_WIDTH{1'b0}};
> end
> else
> if( negedge key_i[0] ) begin
> counter_i <= counter_i + 1;
> end
> end
> Так будет правильно?

Нет, negedge может использоваться только при указании сигналов для блока always, внутри уже нет. Кроме того, даже если бы вы перенесли negedge key[0] в описание блока always, это все равно было бы неправильно. Просмотрите разработку лабораторной работы еще раз, там говорится об элементе, способном запоминать состояния.

P.S. если вы хотите публиковать код в комментариях, то оформляйте его соответственно:
```
always @( posedge clk100_i or negedge key_i[1] ) begin
  if ( !key_i[1] ) begin
    counter_i <= {DATA_WIDTH{1'b0}};
  end
  else begin
    if( negedge key_i[0] ) begin
      counter_i <= counter_i + 1;
    end
  end
end
```
Для этого вверху у вас есть соответствующая панель. Если её функционала недостаточно чтобы выразить что у вас на уме, можете погуглить о markdown разметке.

2020-05-11 22:26 UTC, HepoH3 requested changes
Судя по тому, что я увидел на времянке, ваше устройство будто реагирует следующим образом:  
Когда кнопка нажимается, увеличивается счетчик, который отображается на семисегментнике.  
Когда кнопка отжимается, происходит вывод на светодиоды значения с sw.  
Таким образом, с семисегментником проблем нет, а вот светодиоды изменяются не тогда, когда нужно. 
Когда это исправите, кажется проблем больше не будет.

2020-05-11 22:26 UTC, HepoH3 commented on lab2/rtl/REG_TEN.v
> +        led_o[DATA_WIDTH-1:0] <= sw_i[DATA_WIDTH-1:0];
Вы можете не указывать здесь разрядность, если используете всю шину.

2020-05-12 13:23 UTC, krsnvir commented
Ну что?

2020-05-12 13:32 UTC, HepoH3 approved these changes
Базовая часть лабы принята.

2020-05-12 13:32 UTC, merged