lab2 general part
HepoH3/MIET_FPGA_practicum pull request #34
Opened 2020-05-07 20:27 UTC by BamblooV

Активный сигнал на сброс и работу - 1 (arst _i  en_i)

2020-05-09 15:09 UTC, HepoH3 requested changes
1) В репозиторий добавляются только исходники. Никаких временных файлов вивадо, за исключением (в редких случая) файлов проекта быть не должно;
2) ![Код-стайл](http://82.179.184.185:82/doku.php?id=verilog_guideline) не соблюден;
3) В исходном репе не дано ничего, что нужно было бы удалять.
4) В исходном репе дан интерфейс, который должен соблюдаться. Раз в папке лежит файл counter.v с описанным внутри модулем и его портами — значит в этом же файле должна появиться реализация именно этого модуля. Потому что другой человек который будет ожидать увидеть именно такой модуль.

Пока топовый модуль не будет соответствовать прототипу, я не смогу проверить его работоспособность.

2020-05-12 06:31 UTC, HepoH3 requested changes
Ваш дизайн реагирует на удерживание кнопки, т.е. пока key[0] находится в нуле, счетчик продолжает считать, а должен считать только после того, как key[0] перешел из единицы в ноль.

2020-05-12 06:31 UTC, HepoH3 commented on lab2/rtl/counter.v
> +end
Схема, которую вы организовали является синхронной. Дешифратор должен быть комбинационным.
Съехали отступы.

2020-05-12 06:42 UTC, BamblooV commented on lab2/rtl/counter.v
> +end
> "Схема, которую вы организовали является синхронной. Дешифратор должен быть комбинационным."
Я  не очень понимаю что требуется и почему. Что значит "должен быть комбинационным"? "является синхронной" это тоже неправильно?

2020-05-12 06:45 UTC, BamblooV commented on lab2/rtl/counter.v
> +end
> 
Схема, которую вы организовали является синхронной. Дешифратор должен быть комбинационным.
> 
Я не очень понимаю что требуется и почему. Что значит "должен быть комбинационным"? "является синхронной" это тоже неправильно?

2020-05-12 06:46 UTC, BamblooV commented on lab2/rtl/counter.v
> +end
> Схема, которую вы организовали является синхронной. Дешифратор должен быть комбинационным.

Я не очень понимаю что требуется и почему. Что значит "должен быть комбинационным"? "является синхронной" это тоже неправильно?

2020-05-12 06:47 UTC, HepoH3 commented on lab2/rtl/counter.v
> +end
Преподаватель говорит, что вы должны быть знакомы с понятиями синхронной и комбинационной логики. Комбинационная логика — это схема без памяти. Она организуется с помощью операции assign, а так же блока always @( * ).
Вы описали синхронную логику — в вашей схеме используется тактирование.

2020-05-12 07:21 UTC, BamblooV commented on lab2/rtl/counter.v
> +end
Я не совсем понимаю принцип работы гита. Из-за того, что в первом коммите был констрейн я теперь не могу его отдельно докинуть. Из-за того что во втором комите я выслал код субмодулей, то теперь сделав небольшие изменения в них я не могу их заново отправить, но изменения в головном файле в пару строк он позволяет его кинуть. Мб закрыть этот реквест и я всё по новой закину?

2020-05-12 07:24 UTC, BamblooV commented on lab2/rtl/counter.v
> +end
И можно перевести общение в какой-нибудь мессенджер, а то крутить постоянно страницу не очень интересно

2020-05-12 08:12 UTC, HepoH3 commented on lab2/rtl/counter.v
> +end
Нет, работа с гитом — это тоже часть обучения, вам все равно придется рано или поздно этим заниматься и лучше уж рано. 
Мы можем пообщаться насчет проблем с гитом в телеге (`@hepoh`), но все вопросы касательно лабы будут по-прежнему здесь. Мне как проверяющему гораздо проще смотреть только в 1 пул-реквест связанный с конкретным человеком и конкретной сдачей лабы, нежели прыгать между окнами месседжеров, браузером и симулятором.

2020-05-12 08:13 UTC, HepoH3 commented on lab2/rtl/counter.v
> +end
> 
> 
> крутить постоянно страницу не очень интересно

Вам должны приходить уведомления по почте, я лично прихожу сюда исключительно по ним.

2020-05-12 14:21 UTC, HepoH3 requested changes
1) Уберите лишние файлы;
2) Уберите индивидуальное задание. Оно в любом случае будет пушиться не в этом пулреквесте, и базовая часть в любом случае еще не работает.
3) В базовой части счетчик реагирует на любое изменение кнопки. Счетчик что я брал для проверки находился не в папке Inidividual.
4) Ledr реагирует на отжатие кнопки, а должно быть наоборот.

2020-05-12 14:21 UTC, HepoH3 commented on lab2 Individual Task/rtl/pmodule_register.v
> +always @( posedge arst_i or negedge arst_i ) begin
Вместо этого достаточно просто написать always @( arst_i)

2020-05-13 08:22 UTC, HepoH3 requested changes

2020-05-13 08:22 UTC, HepoH3 commented on lab2/rtl/module_counter.v
> + always @( negedge en_i) begin
Не-а, так дело не пойдет. В разработке лабораторной была описана нужная схема. Никаких negedge для key[0].

2020-05-13 08:22 UTC, HepoH3 commented on lab2/rtl/module_register.v
> +end
См. выше.

2020-05-13 09:23 UTC, HepoH3 requested changes
По заданию ваш дизайн должен реагировать на нажатие кнопки, а не ее удержание.  
![](https://puu.sh/FJQgj/f3adaae9fc.png)

2020-05-13 09:34 UTC, BamblooV commented
Если делать, чтобы он реагировал на нажатие кнопки, то это как в предыдущем варианте, но он забракован из-за несоотвествия примеру из разработки

2020-05-13 09:38 UTC, HepoH3 commented
> 
> 
> Если делать, чтобы он реагировал на нажатие кнопки, то это как в предыдущем варианте, но он забракован из-за несоотвествия примеру из разработки

Он был забракован из-за того что используется `negedge(key[0])`. Во-первых, он был нерабочий, поскольку изменения были несинхронные, во вторых есть и другие способы понять, что раньше кнопка была не нажата, а теперь нажата, помимо отрицательного фронта сигнала.

2020-05-13 11:48 UTC, HepoH3 commented
Теперь дизайн реагирует на отжатие. Блин мы топчемся на месте уже четыре ревью. Ваш дизайн должен реагировать на нажатие кнопки. Активный уровень у кнопки — ноль. Это значит что раньше кнопка должна была быть в состоянии 1, а потом в состоянии 0. Но при этом вы не должны использовать `negedge key[0]`.

2020-05-13 11:48 UTC, HepoH3 commented
Теперь дизайн реагирует на отжатие. Блин мы топчемся на месте уже четыре ревью. Ваш дизайн должен реагировать на нажатие кнопки. Активный уровень у кнопки — ноль. Это значит что раньше кнопка должна была быть в состоянии 1, а потом в состоянии 0. Но при этом вы не должны использовать `negedge key[0]`.

2020-05-13 12:21 UTC, HepoH3 approved these changes
Отлично. Базовая часть засчитана.

2020-05-13 12:21 UTC, HepoH3 commented on lab2/rtl/counter.v
> +          endcase
Отступы съехали.

2020-05-13 12:21 UTC, merged