Vt21 apolihin
HepoH3/MIET_FPGA_practicum pull request #35
Opened 2020-05-07 20:49 UTC by DedushkaGnom

Активный уровенб arst_i ( Асинхронный сброс ) и en_i ( Enable ) равен единице.

2020-05-09 15:12 UTC, HepoH3 requested changes
1) В репозиторий добавляются только исходники. Никаких временных файлов вивадо, за исключением (в редких случая) файлов проекта быть не должно;
2) ![Код-стайл](http://82.179.184.185:82/doku.php?id=verilog_guideline) не соблюден;
3) В исходном репе не дано ничего, что нужно было бы удалять.
4) В исходном репе дан интерфейс, который должен соблюдаться. Раз в папке лежит файл counter.v с описанным внутри модулем и его портами — значит в этом же файле должна появиться реализация именно этого модуля. Потому что другой человек который будет ожидать увидеть именно такой модуль.
5) Коммиты должны быть ![наполнены смыслом](https://habr.com/ru/post/416887/), а они не должны дублироваться.

Пока топовый модуль не будет соответствовать прототипу, я не смогу проверить его работоспособность.

2020-05-09 15:12 UTC, HepoH3 commented on lab2/rtl/counter.v
> +end
Конфликт пула.

2020-05-09 15:12 UTC, HepoH3 commented on lab2/rtl/main.v
> +>>>>>>> Stashed changes
конфликт

2020-05-09 15:12 UTC, HepoH3 commented on lab2/rtl/main.v
> +=======
в общем, на остальные конфликты уже обращать внимания не буду

2020-05-13 11:54 UTC, HepoH3 requested changes

2020-05-13 11:54 UTC, HepoH3 commented on lab2/rtl/Main_counter.v
> +  );
Вы не должны удалять данные в исходном репозитории файлы. Данный модуль должен быть реализован в файле `counter.v`.

2020-05-13 16:36 UTC, DedushkaGnom commented
Нормально сейчас?

2020-05-14 07:25 UTC, HepoH3 requested changes
В данный момент ledr обновляется пока кнопка не нажата.

2020-05-14 07:25 UTC, HepoH3 commented on lab2/rtl/Reg_Led.v
> +  end
Обратите внимание, что активным уровнем у кнопок является ноль. Кроме того, по заданию ваш дизайн должен реагировать на нажатие кнопки, а не ее удержание. Таким образом, вас должен интересовать момент, когда key[0] переходит из состояния 1 в состояние 0.

2020-05-14 08:24 UTC, DedushkaGnom commented
Сейчас исправлю нормально led'ы. Понял, что я просто поменял фронт, но не исправил, чтобы было на нажатие, а не удержание

2020-05-14 08:35 UTC, DedushkaGnom commented
Вроде всё исправил

2020-05-14 11:07 UTC, HepoH3 requested changes
Данный пул-реквест относится к базовой части лабораторной работы. Уберите отсюда реализацию индивидуального задания, оно сдается после базовой части проверяется в отдельном пул-реквесте.

2020-05-14 11:29 UTC, HepoH3 commented
Вы все еще не убрали индивидуальную часть из своего пул-реквеста.

2020-05-14 12:11 UTC, DedushkaGnom commented
Убрал

2020-05-14 12:36 UTC, HepoH3 approved these changes
Зачтено.

2020-05-14 12:36 UTC, merged