vt21_Borisov_Lab2
HepoH3/MIET_FPGA_practicum pull request #39
Opened 2020-05-07 21:20 UTC by Plashaha

2020-05-09 15:36 UTC, HepoH3 requested changes
Пока топовый модуль не будет соответствовать прототипу, я не смогу проверить его работоспособность.

2020-05-09 15:36 UTC, HepoH3 commented on lab2/rtl/counter.v
> +end
Если это выполнение индивидуального задания, то в данном пул-реквесте оно не требуется.

2020-05-09 15:36 UTC, HepoH3 commented on lab2/rtl/counter.v
> +    );
Данный вам модуль counter — это не регистр-счетчик, а называние вашего итогового устройства. Прототип этого модуля не нужно менять. Потому что другой человек который будет ожидать увидеть именно такой модуль.

2020-05-09 15:36 UTC, HepoH3 commented on lab2/rtl/main.v
> +
Здесь в частности, и в остальных местах в целом, не соблюден данный вам кодстайл.

2020-05-13 18:36 UTC, Plashaha commented
Можно приступать к индивидуальному заданию или что-то надо исправить? Просто времени не так много осталось

2020-05-14 07:40 UTC, HepoH3 approved these changes
Можете приступать к индивидуальному заданию.

2020-05-14 07:41 UTC, merged