Update
HepoH3/MIET_FPGA_practicum pull request #40
Opened 2020-05-07 22:14 UTC by lobi112

Добавление файлов

2020-05-09 15:38 UTC, HepoH3 requested changes
1) В репозиторий добавляются только исходники. Никаких временных файлов вивадо, за исключением (в редких случая) файлов проекта быть не должно;
2) В исходном репе дан интерфейс, который должен соблюдаться. Раз в папке лежит файл counter.v с описанным внутри модулем и его портами — значит в этом же файле должна появиться реализация именно этого модуля. Потому что другой человек который будет ожидать увидеть именно такой модуль.
3) Коммиты должны быть [наполнены смыслом](https://habr.com/ru/post/416887/), а не вот эта фигня, что я вижу выше.

Пока топовый модуль не будет соответствовать прототипу, я не смогу проверить его работоспособность.

2020-05-09 17:30 UTC, lobi112 commented
> 1. В репозиторий добавляются только исходники. Никаких временных файлов вивадо, за исключением (в редких случая) файлов проекта быть не должно;
> 2. В исходном репе дан интерфейс, который должен соблюдаться. Раз в папке лежит файл counter.v с описанным внутри модулем и его портами — значит в этом же файле должна появиться реализация именно этого модуля. Потому что другой человек который будет ожидать увидеть именно такой модуль.
> 3. Коммиты должны быть наполнены смыслом а не вот эта фигня, что я вижу выше.
> 
> Пока топовый модуль не будет соответствовать прототипу, я не смогу проверить его работоспособность.

1)Это вопрос про gitignore? Я так и не понял, в каком моменте его использовать и предположил, что он уже встроен в вашем репозитории. Если нет, объясните, что делать. Просто до этого я его загружал при создании нового репозитория, как его установить на уже существующий, не знаю.
2)Не понял, что вы хотите. tb для каждого модуля? И если так, зачем? Всё равно вся их работа заключена в main.
3)Уточните, каким именно смыслом. Приведите пример
P.S. Что вы подразумеваете под топовым модулем, и о каком прототипе речь?

2020-05-09 18:40 UTC, HepoH3 commented
1) В вашем пул-реквесте 87 файлов. Все то, что автоматически создал vivado вы пушить не должны. Не пушить вы можете, добавив руками только то что нужно, либо замаскировав ненужное с помощью .gitignore. В репе его нет, но вы можете его создать и запушить, это один из тех файлов, которые допускаются к пушу.
2) Представьте, что вас попросили сделать прямоугольную коробочку с красной, синей и зеленой кнопками. Когда нажимается красная кнопка, выводится цифра 1, когда синяя, выводится цифра 2, когда зеленая — выводится цифра 3.
Заказчик ожидает, что он получит именно такую коробочку, потому что в проекте, который он использует сидит человек, который умеет только различать эти три цвета. Однако вместо этого, вы принесли ему круглый диск, который выводит цифру 1, когда ты по нему хлопаешь, цифру 2 когда ты его катаешь и цифру 3, когда ты засовываешь его в печь. Вроде бы он и выводит цифры 1, 2, 3, и для каждой цифры требуется определенное действие, но это не то, что хотел заказчик.
Вот считайте, что форма коробки — это название модуля. Вас попросили сделать модуль counter (прямоугольная коробочка), а вы принесли модуль main. Цвета кнопочек — это названия портов. Надеюсь, метафора исчерпывающая.

2020-05-11 19:48 UTC, lobi112 commented
Полностью поменял структуру лабы. За непонимание того, что от меня требовал прошлый комментарий, оставил всего один модуль. Теперь проблем с кнопками быть не должно. 
Добавил gitignore.

"Учиться самому, может иногда и интересно, но совершенно не практично. Хорошим пилотом не станешь, разбив несколько самолётов и научившись на своих ошибках. У хирурга должен быть учитель, он не должен вырезать аппендикс один за другим, чтобы понять, как это делается и какие здесь возможны ошибки. Надеюсь, метафора исчерпывающая."

2020-05-11 22:15 UTC, HepoH3 requested changes
Вы конечно можете быть бесконечно остроумными, но меня это совершенно не трогает. Я постарался объяснить максимально на пальцах в чем была ваша проблема, если не получилось — ну извиняйте. От меня требуется лишь проверить лабораторные работы и ваша пока что проверки не проходит. С вашими сообщениями к коммитам я вам от всей души желаю счастья и крепких нервов, они вам в будущем понадобятся, если вы будете продолжать в том же духе. Я требую писать нормальные сообщения не потому что мне это по кайфу, а потому что вам нужно выработать привычку делать определенные вещи, даже если это влом, чтобы потом не тратить недели своего времени на то, чтобы разобраться в том, что вы делали полгода назад.

2020-05-11 22:15 UTC, HepoH3 commented on lab2/tmp/vivado.log
> +#-----------------------------------------------------------
Этот файл тут не нужен.

2020-05-11 22:15 UTC, HepoH3 commented on lab2/tmp/vivado.jou
> +# Journal file: C:/Users/Shell/Desktop/Lab_2_v3/tmp\vivado.jou
Аналогично комментарию выше.

2020-05-11 22:15 UTC, HepoH3 commented on lab2/tmp/vivado.jou
> +# Journal file: C:/Users/Shell/Desktop/Lab_2_v3/tmp\vivado.jou
Тоже самое.

2020-05-11 22:15 UTC, HepoH3 commented on lab2/tmp/Lab_2_v3.sim/sim_1/behav/xsim/glbl.v
> +//--------   STARTUP Globals --------------
Тоже самое.

2020-05-11 22:15 UTC, HepoH3 commented on lab2/rtl/counter.v
> +  always @( posedge clk100_i or negedge push_b1 ) begin
Смотрите, сначала вы делаете `assign push_b1 = ~key_i[1];`, а потом здесь используете `negedge` и `!push_b1` . Минус на минус так сказать дает плюс и в итоге ваш дизайн снова работает так, будто у источника ресета активным уровнем является единица, из-за чего, полагаю, дизайн находится в непрерывном ресете и не реагирует на нажатия.

2020-05-11 22:15 UTC, HepoH3 commented on lab2/rtl/counter.v
> +  end
В данной лабораторной это не принципиально, но здесь идет дублирование кода, для избежания которого можно создать отдельный модуль, а здесь использовать два его инстанса.

2020-05-12 13:57 UTC, HepoH3 approved these changes
Отлично, все тесты пройдены без нареканий. Базовая часть зачтена.

2020-05-12 13:57 UTC, merged