lab2
HepoH3/MIET_FPGA_practicum pull request #41
Opened 2020-05-07 22:50 UTC by nikitanvkru

2020-05-09 15:39 UTC, HepoH3 requested changes
1) В репозиторий добавляются только исходники. Никаких временных файлов вивадо, за исключением (в редких случая) файлов проекта быть не должно;
2) ![Код-стайл](http://82.179.184.185:82/doku.php?id=verilog_guideline) не соблюден;
3) В исходном репе дан интерфейс, который должен соблюдаться. Раз в папке лежит файл counter.v с описанным внутри модулем и его портами — значит в этом же файле должна появиться реализация именно этого модуля. Потому что другой человек который будет ожидать увидеть именно такой модуль.


Пока топовый модуль не будет соответствовать прототипу, я не смогу проверить его работоспособность.

2020-05-13 22:26 UTC, nikitanvkru commented
0450ea9 базовая часть

2020-05-14 07:51 UTC, HepoH3 requested changes
В данном пул-реквесте от вас требуется базовая часть. Даже если вы уже выполнили индивидуальное задание, здесь оно принято не будет.  Отменяйте коммиты связанные с ним и буду проверять базовую часть.
В README дана ссылка на статью о том, как следует подписывать коммиты. В дальнейшем, если я буду видеть подобные коммиты снова, будет снижаться балл.

2020-05-15 19:40 UTC, HepoH3 approved these changes
Зачтено.

2020-05-15 19:40 UTC, merged