Ошибки исправлены
HepoH3/MIET_FPGA_practicum pull request #49
Opened 2020-05-09 09:22 UTC by MozFox

2020-05-09 15:58 UTC, frarrr requested changes

2020-05-09 15:58 UTC, frarrr commented on lab2/rtl/hex.v
> +        default:  out = 7'b1111111;
Исправьте табы на пробелы, убедитесь, что для отступа используется два пробела

2020-05-09 15:58 UTC, frarrr commented on lab2/rtl/main.v
> +  end
Модуль без ресета
При добавлении ресета убедитесь, что он асинхронный. Чем он отличается от синхронного можно заметить в [вики](http://82.179.184.185:82/doku.php?id=verilog_guideline)

2020-05-09 15:58 UTC, frarrr commented on lab2/rtl/main.v
> +    button_syncroniser[0] <= btn_i;
Не учитывается, что активный уровень кнопки -- 0

2020-05-09 15:58 UTC, frarrr commented on lab2/rtl/main.v
> +  );
Выровнять лучше так:
```
hex hex0 ( 
  .in  ( counter[3:0] ),
  .out ( hex0_o       )
);
```

2020-05-09 15:58 UTC, frarrr commented on lab2/rtl/main.v
> +  end
Отступ -- 2 пробела

2020-05-10 19:30 UTC, MozFox commented
Исправил код

2020-05-11 09:17 UTC, frarrr requested changes

2020-05-11 09:17 UTC, frarrr commented on lab2/rtl/hex.v
> +	output reg   [6:0]    out
Табы вместо пробелов

2020-05-11 09:17 UTC, frarrr commented on lab2/rtl/main.v
> +      counter = counter + 1;
Блокирующее присваивание

2020-05-11 09:17 UTC, frarrr commented on lab2/rtl/main.v
> +    );
Поправьте название модуля и входов-выходов так, чтобы они соответствовали названиям из [шаблона](https://github.com/HepoH3/MIET_FPGA_practicum/blob/master/lab2/rtl/counter.v).

2020-05-11 11:44 UTC, MozFox commented
Внес изменения

2020-05-11 11:53 UTC, frarrr requested changes

2020-05-11 11:53 UTC, frarrr commented on lab2/rtl/counter.v
> +    );
Обратите внимание на то, что в шаблоне используются две кнопки:
`input [1:0] key_i`
По заданию `key_i[1]` -- это общий асинхронный ресет, `key_i[0]` -- инкрементирует счетчик.
Вход `rstn_i` в задании не используется

2020-05-11 12:59 UTC, MozFox commented
Исправил

2020-05-11 13:12 UTC, frarrr commented
Принято

2020-05-11 13:12 UTC, merged