lab2_ver2 (hex_on_o -> hex0_o and hex1_o)
HepoH3/MIET_FPGA_practicum pull request #50
Opened 2020-05-09 11:38 UTC by capython59

2020-05-09 15:04 UTC, frarrr commented
У вас происходит срабатывание по отпусканию кнопки, а не по нажатию, скорее всего из-за того, что перепутан активный уровень. У обеих кнопок это 0.

2020-05-09 15:09 UTC, frarrr requested changes
В целом все хорошо, поправьте срабатывание кнопки и codestyle

2020-05-09 15:09 UTC, frarrr commented on lab2/rtl/hex.v
> +        output         reg   [6:0]    out
Съехало выравнивание

2020-05-09 15:09 UTC, frarrr commented on lab2/rtl/hex.v
> +        default:  out = 7'b1111111;
Здесь тоже используются табы вместо пробелов

2020-05-09 15:09 UTC, frarrr commented on lab2/rtl/main.v
> +  end
Блок синхронной логики без ресета

2020-05-09 15:09 UTC, frarrr commented on lab2/rtl/main.v
> +        reg_mass <= 10'd0;
Большой отступ

2020-05-09 15:09 UTC, frarrr commented on lab2/rtl/main.v
> +  );
Вот так корректнее:
```
hex hex0 ( 
  .in  ( counter[3:0] ),
  .out ( hex0_o       )
);
```

2020-05-10 13:01 UTC, capython59 commented
Исправил code style и срабатывание кнопки

2020-05-10 14:46 UTC, frarrr requested changes

2020-05-10 14:46 UTC, frarrr commented on lab2/rtl/hex.v
> +	4'hf:     out = 7'b0001110;
Табы вместо пробелов

2020-05-10 14:46 UTC, frarrr commented on lab2/rtl/main.v
> +assign key_pressed_true = ~button_sync[2] & button_sync[1];
Здесь детектируется момент, когда кнопка отпускается, а не нажимается, из-за того что кнопка считается нажатой при активном уровне 0 и считается не нажатой -- при 1

2020-05-11 14:24 UTC, capython59 commented
Должно все работать теперь

2020-05-11 15:05 UTC, frarrr commented
Все еще остались табы в модуле hex, в остальном все верно

2020-05-11 15:06 UTC, frarrr requested changes

2020-05-11 15:06 UTC, frarrr commented on lab2/rtl/hex.v
> +  case (in)
Здесь еще стоит пробелы добавить между скобками и их содержимым

2020-05-11 15:21 UTC, frarrr commented
Принято

2020-05-11 15:21 UTC, merged