kiselev_alexander
HepoH3/MIET_FPGA_practicum pull request #52
Opened 2020-05-09 16:56 UTC by kiselev21

исправил недочеты

2020-05-09 17:16 UTC, kiselev21 commented
Извиняюсь,не добавил тест бенч,но он у меня есть,просто в предыдущем письме вы писали что будете своим тестить и я не обратил внимание на его добавление в репозиторий

2020-05-09 18:31 UTC, HepoH3 requested changes
Намного лучше того, что было раньше. Уберите индивидуальную задачу, запушьте исправление и буду проверять работоспособность.

2020-05-09 18:31 UTC, HepoH3 commented on lab2/rtl/counter.v
> +end
Судя по всему, это выполнение индивидуального задания. В данном пул-реквесте оно не требуется.

2020-05-09 18:43 UTC, kiselev21 commented
А можно будет вам завтра в первой половине дня прислать исправление?

2020-05-09 18:55 UTC, HepoH3 commented
Вопросы по дедлайнам следует адресовать Александру Михайловичу, мне лично без разницы.

2020-05-10 10:44 UTC, kiselev21 commented
Здравствуйте,запушил изменения,убрал индивидуальное задание.

2020-05-10 11:08 UTC, HepoH3 requested changes

2020-05-10 11:08 UTC, HepoH3 commented on lab2/rtl/counter.v
> +  end
Здесь имеет место дублирование кода, что не есть хорошо. Для данной работы это не принципиально, но на будущее: в подобных случаях лучше вынести блок в отдельный модуль и подключить тут два инстанса этого модуля.

2020-05-10 11:08 UTC, HepoH3 commented on lab2/rtl/counter.v
> +   end
Реакция дизайна должна происходить по нажатию на кнопку, а не по ее удержанию. Если кнопку нажмут и будут держать 4 такта ваш дизайн увеличит счетчик на 4, а увеличиться он должен на 1 вне зависимости от длительности нажатия.

2020-05-10 11:47 UTC, kiselev21 commented on lab2/rtl/counter.v
> +   end
я так понял,что нужно убрать дребезжание?

2020-05-10 11:53 UTC, HepoH3 commented on lab2/rtl/counter.v
> +   end
В строчках выше сказано увеличить счетчик по каждому положительному фронту клока, если key_i[0] находится в нуле. Если нажать и держать кнопку, счетчик будет увеличиваться каждый такт. Надо сделать так, чтобы счетчик увеличился только в первый такт нажатия на кнопку, это не связано с дребезгом.

2020-05-10 13:59 UTC, kiselev21 commented on lab2/rtl/counter.v
> +   end
Исправил,добавил модуль debounce

2020-05-10 14:28 UTC, kiselev21 commented on lab2/rtl/counter.v
> +   end
Я исправил лабу,мне кажется,что я получил тот результат,который вы хотели,но там задержка 2 такта ,так как каждый такт клока сигнал проходил только через 1 триггер а у меня их 2

2020-05-10 15:29 UTC, HepoH3 commented on lab2/rtl/counter.v
> +   end
Это нормально

2020-05-10 15:31 UTC, HepoH3 approved these changes
Поздравляю, тесты пройдены, базовая часть лабораторной засчитана.

2020-05-10 15:31 UTC, merged

2020-05-10 15:35 UTC, kiselev21 commented
А индивидуальную часть у вас брать или у Александра Михайловича?

2020-05-10 15:37 UTC, HepoH3 commented
> 
> 
> А индивидуальную часть у вас брать или у Александра Михайловича?

У Александра Михайловича, все организационные вопросы надлежит адресовать ему, я всего лишь проверяльщик. Возможно, вам достаточно вернуть то что вы выполнили ранее, не знаю.