Vt21 bogdanov Версия 3
HepoH3/MIET_FPGA_practicum pull request #60
Opened 2020-05-09 23:36 UTC by DROZD-01

На sw[10] теперь повешена функция вкл./выкл. функции debounce. При 0 она выключена, и происходит только синхронизация с clk_50m.
Теперь debouncing и синхронизация являются отдельными модулями. Исправлены некоторые ошибки в codestyle.

2020-05-10 12:41 UTC, DROZD-01 commented
Внимание! пока проверять не надо до следующего коммита. Забыл исправить #задержку в одном из модулей.

2020-05-10 14:13 UTC, DROZD-01 commented
Готово! Можно проверять.

2020-05-11 10:45 UTC, frarrr requested changes
Для кнопки, которая является ресетом в целом не нужно детектировать нажатие, достаточно сбрасывать значения регистров все время, пока она нажата. Плюс условие `negedge key[1]` уже будет определять момент, когда кнопка была нажата и ресет сработает без дополнительных задержек

2020-05-11 10:45 UTC, frarrr commented on lab2/project_lab_2/rtl/button_synchronizer.v
> +    end
Здесь вы почти реализовали схему детектирования нажатия, но перепутали условие `btn_clk_o`
В вашем случае `btn_clk_o `-- это задержанный на два такта сигнал о том, что кнопка нажата. То есть если вы дальше будете передавать его на счетчик, например, но он будет инкрементироваться все время, пока кнопка нажата

2020-05-11 10:45 UTC, frarrr commented on lab2/project_lab_2/rtl/hub.v
> +  keys_debounce u1(
Для инстансов лучше выбирать названия, которые что-то говорят о подключаемом модуле. Так проще ориентироваться в дизайне, потому что САПР будет обращаться к модулю как u1, а не как keys_debounce. Но это на ваше усмотрение

2020-05-11 10:45 UTC, frarrr commented on lab2/project_lab_2/rtl/mainframe.v
> +    );
Лучше все же переименовать название модуля и входов-выходов так, чтобы они соответствовали названиям из [шаблона](https://github.com/HepoH3/MIET_FPGA_practicum/blob/master/lab2/rtl/counter.v).
Нет смысла обрабатывать нажатия 5 кнопок, когда нужны только 2. Переключатель sw[10] можете оставить, так как он вам нужен

2020-05-11 10:45 UTC, frarrr commented on lab2/project_lab_2/rtl/switch_event.v
> +            sw_event <= 1'b0;
Здесь надо либо использовать блокирующее присваивание, так как это комбинационная логика, либо тактировать блок always по clk

2020-05-11 10:45 UTC, frarrr commented on lab2/project_lab_2/rtl/switch_event.v
> +    end
Модуль без ресета

2020-05-11 10:45 UTC, frarrr commented on lab2/project_lab_2/rtl/switch_event.v
> +    wire event_reg_sum = &event_sync_reg[1:0];
В соответствии с codestyle-ом, wire объявляется в одной строке, а значение ему присваивается в другой

2020-05-11 10:45 UTC, frarrr commented on lab2/project_lab_2/rtl/keys_debounce.v
> +    );// ������ btn_i[0] ��� KEY[0]
Здесь отступ больше, чем нужен

2020-05-11 10:45 UTC, frarrr commented on lab2/project_lab_2/rtl/keys_debounce.v
> +    );// ������ btn_i[3]
Здесь вам это не понадобится, но в будущем если необходимо будет создать несколько одинаковых модулей, можете воспользоваться такой записью:
```
  localparam BUTTON_NUM = 4;
  
  generate
    genvar i;
    for ( i = 0; i < BUTTON_NUM - 1; i = i + 1'b1 )
      begin: gen_btn_sync
        button_synchronizer btn_sync (
          .btn_i      (  btn_i[i]      ),
          .rst_i      (  btn_rst_o     ),
          .btn_clk_o  (  btn_clk[i]    ),
          .clk_i      (  clk_50m       )  
        );
      end
  endgenerate
```

2020-05-11 10:48 UTC, frarrr commented
Да, также не стоит хранить файлы проекта в репозитории, это засоряет его отслеживанием неинформативных изменений. Просто удалите папку и добавьте ее в .gitignore

2020-05-11 11:09 UTC, DROZD-01 commented
Я использую .gitignore от авторов Vivado. Требования к шаблону уже несколько раз менялись, и в прошлый раз вопросов к вводу-выводу из заголовочного модуля не было. button_synchronizer переделаю так же, как синхронизацию с кнопкой в switch_event.

2020-05-11 11:36 UTC, frarrr commented
> Я использую .gitignore от авторов Vivado.

Можете не менять .gitignore, это исключительно ваш выбор. Но временные файлы хранить в репозитории все еще не стоит, это его засоряет.

> Требования к шаблону уже несколько раз менялись, и в прошлый раз вопросов к вводу-выводу из заголовочного модуля не было. 

Я лично не вижу проблемы в том, что вы используете свои названия модулей и io, пока они соответствуют codestyle-y. Но мои коллеги, как оказалось, видят, и я могу их понять. Предъявлять требования по неймингу другим студентам и не предъявлять их вам было бы не справедливо, поэтому всех, кто еще не защитил лабу, прошу переделать заголовочный файл вместе с остальными изменениями.

2020-05-11 14:53 UTC, DROZD-01 commented
![image](https://user-images.githubusercontent.com/20706726/81575799-1ee3e380-93b0-11ea-9416-b9f7133e3b47.png)
Для какого из двух счётчиков должно применяться второе условие?

2020-05-11 15:07 UTC, frarrr commented
> Для какого из двух счётчиков должно применяться второе условие?

Для обоих

2020-05-11 16:27 UTC, DROZD-01 commented
Что насчёт исправлений?

2020-05-11 17:06 UTC, frarrr commented
> Что насчёт исправлений?

Пока вы исправили только часть замечаний. Когда закончите с остальными, напишите сообщение об этом или просто запросите ревью

2020-05-11 20:11 UTC, DROZD-01 commented
![image](https://user-images.githubusercontent.com/20706726/81607013-a9423c80-93dc-11ea-890a-c79dc70c5abe.png)
Исправьте таблицу с индивидуальными заданиями. не бывает 8'b55. Либо тут должна быть "d", либо нужно переписать 55 в бинарном виде.

2020-05-12 08:58 UTC, frarrr requested changes
Не помню, упоминалось ли, но в репозитории не должно храниться лишних файлов -- в вашем случае там лежат файлы проекта
Также обратите внимание, что в lab2 кроме директории project_lab_2 у вас ничего не лежит и в целом не должно. Удалите лишнюю папку в пути, репозиторий станет чище

2020-05-12 08:58 UTC, frarrr commented on lab2/project_lab_2/rtl/mainframe.v
> +    );
Нет никакого смысла в том, чтобы выборочно изменять названия модулей и портов. Смысл использования наименований шаблона в унификации: тогда ваш модуль можно встроить в дизайн, не зная его содержимого.
Есть требования по наименованию, пожалуйста, придерживайтесь их. С учетом того, что ваш дизайн еще нужно проверять на работоспособность основной части, а _только_ потом и индивидуального задания, давайте не будем тратить время друг друга и ускорим проверку.
Убедитесь, что если следующим образом подключить ваш дизайн в тб:
```
counter uut(
    .clk100_i ( clk             ),
    .sw_i     ( {1'b0, sw[9:0]} ),
    .key_i    ( key[1:0]        ),
    .ledr_o   ( ledr            ),
    .hex1_o   ( hex1            ),
    .hex0_o   ( hex0            )
);   
```
он будет работать так, как вы ожидаете.

2020-05-12 08:58 UTC, frarrr commented on lab2/project_lab_2/rtl/mainframe.v
> +    .counter_2_o  (  counter_2[7:0]  )
Не выравнены скобки

2020-05-12 08:58 UTC, frarrr commented on lab2/project_lab_2/rtl/button_synchronizer.v
> +          sync_block  <= 1'b0;
* Нет пробелов между скобками и словами, обращайте внимание на codestyle.
* Даже если условия в разных `if` не пересекаются, если в них присваиваются значения одним и тем же регистрам, для безопасности стоит писать `else if`

2020-05-12 08:58 UTC, frarrr commented on lab2/project_lab_2/rtl/counter_8.v
> +        else if (en_i) counter_o <= counter_o + 1;
Более читаемо перенести присваивания на следующую строку

2020-05-12 08:58 UTC, frarrr commented on lab2/project_lab_2/rtl/debouncer.v
> +    end
Отступ должен быть 2 пробела

2020-05-12 08:58 UTC, frarrr commented on lab2/project_lab_2/rtl/debouncer.v
> +            if (max)
Нет пробелов возле скобок

2020-05-12 08:58 UTC, frarrr commented on lab2/project_lab_2/rtl/debouncer.v
> +            if (max)
В других файлах тоже проверьте это

2020-05-12 08:58 UTC, frarrr commented on lab2/project_lab_2/rtl/debouncer.v
> +    end
Аналогично в других файлах

2020-05-12 10:46 UTC, DROZD-01 commented on lab2/project_lab_2/rtl/mainframe.v
> +    );
Учитывая, что в самой лабораторной работе (а именно Workbook) указана тактовая частота в 50МГц, называть её "clk100_i" - бред. Убирание hex_on_o - то же самое. Он требуется для работы на оборудовании, но мы его убираем. Называть основной модуль "counter"ом - бред абсолютный. Этот модуль ничего не считает и не собирается считать ни в каком виде. Это модуль для объединения остальных модулей и не может ничего считать, так как в нём ничего нет и не будет для этого.

2020-05-12 11:44 UTC, frarrr commented on lab2/project_lab_2/rtl/mainframe.v
> +    );
У шаблона есть приоритет над лабораторной.
Вы также не учитываете то, что дизайн предполагается проверять только на моделировании.
Для того, чтобы предположить, почему модуль называется counter, достаточно перечитать задание.
Вы можете использовать или не использовать заглавный модуль для объединения других модулей -- это не обязательное условие.

Еще раз: главное, соответствие требованиям по оформлению кода и репозитория и по корректности работы дизайна. Пока ваш модуль все еще нельзя подключить описанным выше способом

2020-05-12 11:45 UTC, frarrr commented
Часть исправлений еще не сделана: обратите внимание, что требования по codestyle-у распространяются на весь код, а не только на указанные выше фрагменты

2020-05-12 11:52 UTC, DROZD-01 commented
> Часть исправлений еще не сделана: обратите внимание, что требования по codestyle-у распространяются на весь код, а не только на указанные выше фрагменты

Проверены все модули на отсутствие правильных отступов/скобок. Если что-то я пропустил - прошу указать.

2020-05-12 12:03 UTC, DROZD-01 commented on lab2/project_lab_2/rtl/mainframe.v
> +    );
> Для того, чтобы предположить, почему модуль называется counter, достаточно перечитать задание.

Пояснение "просто потому, что мы его так сначала назвали" - не пояснение. Называть модуль так, чтобы это не соответствовало его функции - нарушение кодстайла.

2020-05-12 12:10 UTC, frarrr requested changes

2020-05-12 12:10 UTC, frarrr commented on lab2/rtl/debouncer.v
> +        if (max)
Здесь забыли пробелы между скобками и содержимым

2020-05-12 12:10 UTC, frarrr commented on lab2/rtl/decoder_8.v
> +          4'd7  : segment_0_o = 7'b111_1000;
Большой отступ

2020-05-12 12:10 UTC, frarrr commented on lab2/rtl/hub.v
> +    if (btn_push[0] || btn_push[1]) begin
Здесь тоже нужны пробелы

2020-05-12 12:10 UTC, frarrr commented on lab2/rtl/switch_event.v
> +            sw_event = 1'b0;
Здесь нарушены отступы

2020-05-12 12:14 UTC, frarrr commented on lab2/project_lab_2/rtl/mainframe.v
> +    );
Здесь не стоит додумывать: ни задания, ни реплики. Задание лабораторной просит вас разработать устройство, которое выводит на 7-сегментники количество нажатий кнопки.
Что является нарушением codestyle, а что нет, позвольте решать проверяющим. Если у вас есть сомнения в правильности решения, можете обратиться к руководителю курса

2020-05-12 16:14 UTC, frarrr commented on lab2/rtl/debouncer.v
> +    reg         state_o = 0;
Не стоит записывать начальное значение в регистр при обявлении, разные САПР могут обрабатывать эту запись по-разному: где-то эта конструкция несинтезируема, где-то -- игнорируется. Лучше всего присваивать начальное значение во время ресета

2020-05-12 16:14 UTC, frarrr commented on lab2/rtl/hub.v
> +  end
Это модуль без ресета, не забывайте описывать логику сброса

2020-05-12 16:14 UTC, frarrr commented on lab2/rtl/counter.v
> +    );
Создание модулей-оберток должно быть обосновано с точки зрения дизайна, в вашем случае причины его создавать -- нет.

2020-05-12 16:14 UTC, closed without merging

2020-05-12 16:38 UTC, DROZD-01 commented on lab2/rtl/hub.v
> +  end
Ресет тут был, но он не был занесён в @(posedge). Исправим.

2020-05-12 16:42 UTC, frarrr commented on lab2/rtl/hub.v
> +  end
Чтобы это воспринималось САПРом как ресет, нужен `else if` после первого `if`

2020-05-12 16:43 UTC, frarrr commented on lab2/rtl/hub.v
> +  end
Плюс нет смысла детектировать нажатие кнопки ресета, можно все время сброса обнулять значения

2020-05-12 16:45 UTC, frarrr commented on lab2/rtl/hub.v
> +  end
Стоит еще учитывать, что сигналы reset, enable, clock в целом лучше описывать как можно очевиднее для синтезатора. Так как `synced_event` относится не столько к ресету, сколько к логике, лучше его во второй if перенести

2020-05-12 16:46 UTC, DROZD-01 commented on lab2/rtl/counter.v
> +    );
Это был самый простой способ не удаляя ничего из кода адаптировать его к вашему тестбенчу. и это работает.

2020-05-12 16:51 UTC, frarrr commented on lab2/rtl/counter.v
> +    );
Тем не менее это плохая манера при создании дизайна
Вашей задачей было не адаптировать ваш проект, который решает поставленную вами задачу под эту лабораторную

2020-05-12 16:53 UTC, frarrr commented on lab2/rtl/counter.v
> +    );
В любом случае, с учетом количества попыток и игнорирования замечаний, у вас стоит 0 баллов за эту лабораторную

2020-05-12 16:54 UTC, DROZD-01 commented on lab2/rtl/hub.v
> +  end
Ненене. synced event - это не ресет. Он там нужен для выбора между счётчиками и сброса этого выбора. Общий ресет там - btn_push[4].

2020-05-12 16:54 UTC, DROZD-01 commented on lab2/rtl/hub.v
> +  end
Его можно переименовать, если требуется, через assign.