Vt23 klimashin
HepoH3/MIET_FPGA_practicum pull request #62
Opened 2020-05-10 15:33 UTC by unclefalkon

2020-05-11 12:08 UTC, frarrr requested changes
Удалите, пожалуйста, файлы проекта vivado из репозитория -- они его засоряют

2020-05-11 12:08 UTC, frarrr commented on lab2/rtl/counter.v
>  );
Выравните открывающие скобки по вертикали

2020-05-11 12:08 UTC, frarrr commented on lab2/rtl/counter.v
> +  .out( hex0_o       )
Нужен пробел между скобкой и словом

2020-05-11 12:08 UTC, frarrr commented on lab2/rtl/dectohex.v
> +		4'hf : out = 7'b0001110;
Табы вместо пробелов

2020-05-11 12:08 UTC, frarrr commented on lab2/rtl/dectohex.v
> +  case(in)
Нужны пробелы между словами и скобками

2020-05-11 12:08 UTC, frarrr commented on lab2/rtl/counter.v
> +    input         clk_i,
`clk100_i`

2020-05-11 13:25 UTC, unclefalkon commented on lab2/rtl/dectohex.v
> +		4'hf : out = 7'b0001110;
Здесь имеется ввиду, что я должен убрать табы и поставить вместо них пробелы?

2020-05-11 13:41 UTC, frarrr commented on lab2/rtl/dectohex.v
> +		4'hf : out = 7'b0001110;
Да, у вас там используется 2 таба для отступа, а в соответствии с codestyle-ом нужно только 2 пробела

2020-05-11 19:38 UTC, unclefalkon commented
Исправил код-стайл, вернул оригинальное имя переменной, удалил папку tmp

2020-05-12 08:28 UTC, frarrr commented
Принято

2020-05-12 08:29 UTC, merged