ИВТ-23 Азиз Шокири
HepoH3/MIET_FPGA_practicum pull request #65
Opened 2020-05-10 18:35 UTC by Lipkoffsky

Лаба 2 исправленная

2020-05-11 12:37 UTC, frarrr requested changes
Помимо перечисленного ниже, удалите файлы проекта из репозитория, из изменение не несет полезной информации

2020-05-11 12:37 UTC, frarrr commented on lab2/rtl/Debounce.v
> +module Debounce(
Для наименования модулей используется snake_case, поправьте здесь и в модуле DecToHex

2020-05-11 12:37 UTC, frarrr commented on lab2/rtl/Debounce.v
> +      sync[1] <= sync[0];
Здесь нужны отступы

2020-05-11 12:37 UTC, frarrr commented on lab2/rtl/DecToHex.v
> +endmodule
Если вы описываете блок синхронной логики, то внутри него стоит использовать неблокирующее присваивание

2020-05-11 12:37 UTC, frarrr commented on lab2/rtl/counter.v
> +  .data_o           ( ledr_o      [9:0] )
Здесь необязательно указывать границы sw_i и ledr_o, потому что они точно совпадают с разрядностью портов модуля register

2020-05-11 12:37 UTC, frarrr commented on lab2/rtl/counter.v
> +  .en_i             ( key_i       [0]   ),
По заданию, обновлять значение регистра тоже нужно только по _нажатию_ кнопки

2020-05-11 14:07 UTC, frarrr commented on lab2/rtl/DecToHex.v
> +endmodule
Но вообще в этом случае стоит использовать комбинационную логику, то есть переписать на `always ( * )` и убрать условие при ресете

2020-05-11 14:20 UTC, Lipkoffsky commented on lab2/rtl/DecToHex.v
> +endmodule
я переписал с использованием неблокирующего присваивания. для этого случая можно так оставить? вроде все правильно работает

2020-05-11 14:21 UTC, Lipkoffsky commented on lab2/rtl/DecToHex.v
> +endmodule
остальные недочеты тоже исправил, запушил

2020-05-11 14:48 UTC, frarrr commented on lab2/rtl/DecToHex.v
> +endmodule
Корректнее все же переписать, пока проверю все остальное

2020-05-11 14:52 UTC, frarrr commented on lab2/rtl/DecToHex.v
> +endmodule
Вы забыли еще удалить файлы проекта из репозитория, кажется

2020-05-11 16:45 UTC, Lipkoffsky commented on lab2/rtl/DecToHex.v
> +endmodule
я не забыл, я не знаю, как удалить
попытки мои подключить репозитарий в гитбаш тщетны
не знаю в чем проблема, с гитом не особо разобрался.
пушил аплоудом просто

2020-05-11 18:59 UTC, Lipkoffsky commented on lab2/rtl/DecToHex.v
> +endmodule
Файлы удалил

2020-05-11 19:09 UTC, frarrr requested changes

2020-05-11 19:09 UTC, frarrr commented on lab2/rtl/counter.v
> +  .en_up_o      ( key_pressed )
Судя по модулю debounce, провод `key_pressed` должен быть подключен к другому выходу модуля

2020-05-11 19:51 UTC, Lipkoffsky commented on lab2/rtl/counter.v
> +  .en_up_o      ( key_pressed )
исправил

2020-05-12 08:21 UTC, frarrr commented
Принято

2020-05-12 08:21 UTC, merged