Алямовский ИВТ-23
HepoH3/MIET_FPGA_practicum pull request #66
Opened 2020-05-11 11:07 UTC by metanoiia

# Публикуя данный пул-реквест, я гарантирую, что:
1) Я предлагаю к слиянию только файлы с hdl-описанием разрабатываемого вами устройства, а так же тестбенчи для его тестирования. Исключением могут разве что быть (но не обязаны) файлы .gitignore, и файлы констрейнов (.xdc), tcl-скрипты для сборки проекта.
2) Мной не были удалены исходные файлы репозитория;
3) Мной реализовано устройство в соответствии с данным в исходном репозитории прототипом. Таким образом, любой человек, зная исходный файл репозитория сможет подключить моё устройство к своему проекту и все соберётся.
4) Мой код соответствует [кодстайлу](http://82.179.184.185:82/doku.php?id=verilog_guideline);
5) Коммиты в публикуемом мной пулл-реквесте являются [содержательными](https://habr.com/ru/post/416887/);  
6) Перед отправкой пул-реквеста я убедился, что мой проект собирается, и проведя собственные тесты оказался удовлетворён его работой.

2020-05-11 12:49 UTC, frarrr requested changes

2020-05-11 12:49 UTC, frarrr commented on lab2/rtl/counter.v
> +);
Между скобкой и словом ставится пробел, да и в целом лучше выравнять открывающие скобки по вертикали

2020-05-11 12:49 UTC, frarrr commented on lab2/rtl/counter_logic.v
> +end
Вы реализуете одну и ту же логику детектирования нажатия кнопки в этом модуле, и в модуле `counter_logic`. Из-за этого аппаратные затраты вашего дизайна увеличиваются. Попробуйте генерировать сигнал `button_was_pressed` только в одном месте и затем передавать его во все нужные модули

2020-05-11 12:49 UTC, frarrr commented on lab2/rtl/counter_logic.v
> +  else if( button_was_pressed ) counter_o <= counter_o + 1;
Здесь написание в одну строчку не добавляет читаемости, лучше перенести присваивание на новую линию

2020-05-11 13:22 UTC, metanoiia commented on lab2/rtl/counter_logic.v
> +end
то есть написать модуль выработки синхронного сигнала и затем вызывать инстанты этого модуля в счетчике и регистре?

2020-05-11 13:40 UTC, frarrr commented on lab2/rtl/counter_logic.v
> +end
Нет, это не исправит проблему, потому что создавая два инстанса, вы все равно два раза используете одну логику. Вы можете, например, выбрать один модуль, где вам кажется более логичным генерировать `button_was_pressed` и добавить в этот модуль `output button_was_pressed`. Так вы сможете сначала передать сигнал нажатия кнопки в заглавный модуль, а потом как `input button_was_pressed` в другой модуль.

Еще один вариант -- вынести эту общую логику заглавный модуль counter и оттуда уже передавать `button_was_pressed` в два нужных вам модуля

2020-05-11 13:42 UTC, metanoiia commented on lab2/rtl/counter_logic.v
> +end
Второй вариант кажется логичнее. Спасибо!

2020-05-11 17:19 UTC, metanoiia commented
Исправил недочеты по кодстайлу, вынес в отдельный модуль схему выработки синхронного сигнала.

2020-05-11 17:30 UTC, frarrr requested changes
Все работает, осталось исправить пару небольших замечаний

2020-05-11 17:30 UTC, frarrr commented on lab2/rtl/counter_logic.v
> +  else if( btn_is_pressed_i )
Здесь еще нужны пробелы после if

2020-05-11 17:30 UTC, frarrr commented on lab2/rtl/reg_10_bit.v
> +        register_o <= data_i;
А здесь отступ 4 пробела, а не 2

2020-05-12 09:28 UTC, metanoiia commented
Внес правки по кодстайлу, заменил блокирующее присваивание на неблокирующее в модуле дебаунсера.

2020-05-12 09:30 UTC, metanoiia commented
У меня вопрос насчет .gitignore возник: как мне лучше добавить папку в инструкцию? Просто засовывание tmp в файл не изменило ничего. Видимо, я что-то упускаю

2020-05-12 09:40 UTC, frarrr commented
> У меня вопрос насчет .gitignore возник: как мне лучше добавить папку в инструкцию? Просто засовывание tmp в файл не изменило ничего. Видимо, я что-то упускаю

Как-то [так](https://ru.stackoverflow.com/questions/535255/%D0%A3%D0%B4%D0%B0%D0%BB%D0%B8%D1%82%D1%8C-%D1%84%D0%B0%D0%B9%D0%BB-%D0%B8%D0%B7-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D1%8F)
Либо проще -- удалить/переместить папку физически, если она вам не нужна.

2020-05-12 09:45 UTC, metanoiia commented
Понял, большое спасибо

2020-05-12 09:46 UTC, frarrr requested changes

2020-05-12 09:46 UTC, frarrr commented on lab2/rtl/decoder.v
> +    default : hex_o <= 7'b1111111;
Здесь вы описываете комбинационную логику, поэтому использовать нужно блокирующее присваивание

2020-05-12 09:46 UTC, frarrr commented on lab2/rtl/decoder.v
> +  case( dec_i )
Все еще нужно добавить пробелы после `if`, `case`

2020-05-12 10:04 UTC, metanoiia commented
Исправил косяки, извиняюсь за затупы. Надеюсь, больше править не придется

2020-05-12 10:09 UTC, frarrr commented
Все хорошо, принято

2020-05-12 10:10 UTC, merged

2020-05-12 10:10 UTC, metanoiia commented
Спасибо