Lab_2 Индивидуальное задание
HepoH3/MIET_FPGA_practicum pull request #69
Opened 2020-05-11 17:20 UTC by nnemountenus

# Публикуя данный пул-реквест, я гарантирую, что:
1) Я предлагаю к слиянию только файлы с hdl-описанием разрабатываемого вами устройства, а так же тестбенчи для его тестирования. Исключением могут разве что быть (но не обязаны) файлы .gitignore, и файлы констрейнов (.xdc), tcl-скрипты для сборки проекта.
2) Мной не были удалены исходные файлы репозитория;
3) Мной реализовано устройство в соответствии с данным в исходном репозитории прототипом. Таким образом, любой человек, зная исходный файл репозитория сможет подключить моё устройство к своему проекту и все соберётся.
4) Мой код соответствует [кодстайлу](http://82.179.184.185:82/doku.php?id=verilog_guideline);
5) Коммиты в публикуемом мной пулл-реквесте являются [содержательными](https://habr.com/ru/post/416887/);  
6) Перед отправкой пул-реквеста я убедился, что мой проект собирается, и проведя собственные тесты оказался удовлетворён его работой.

2020-05-12 07:41 UTC, HepoH3 requested changes

2020-05-12 07:41 UTC, HepoH3 commented on lab2/rtl/counter.v
> +      end
Интересная, но кажется переусложнённая реализация. Если я правильно понял, вы ставите защиту на то, что если счётчик дошел до 100, то дальше он не инкрементируется, этого от вас не требовалось. Он должен продолжать считать, и если произошло переполнение, сброситься вместе с семисегментниками к нулям.  
В остальном все хорошо, как запушите изменения, если от Александра Михайловича еще каких-то дополнительных указаний не будет, можно будет считать лабу сданной.

2020-05-12 13:34 UTC, nnemountenus commented on lab2/rtl/counter.v
> +      end
8)	Выводить значения счетчика от 0 до 99 в десятичном виде на hex0 hex1. При более больших значениях выводить  EE.

По заданию при переполнении ЕЕ вроде должно выводиться, я так и сделал. Обнуление было бы реализовать правда проще.

2020-05-12 14:11 UTC, HepoH3 commented on lab2/rtl/counter.v
> +      end
> 
> 
>     1. Выводить значения счетчика от 0 до 99 в десятичном виде на hex0 hex1. При более больших значениях выводить  EE.
> 
> 
> По заданию при переполнении ЕЕ вроде должно выводиться, я так и сделал. Обнуление было бы реализовать правда проще.

Да, все так, у вас выводится EE. Однако, штука в том, что если продолжать нажимать кнопку, увеличивая счетчик и сделав это еще 155 раз с момента попадания в EE, счетчик должен переполниться и оказаться в значении 0, выведя нули на семисегментник.  
Ваш дизайн так себя не ведет.

2020-05-12 18:03 UTC, HepoH3 requested changes

2020-05-12 18:03 UTC, HepoH3 commented on lab2/rtl/counter.v
>    end
Вы все переусложняете, во первых, ваш дизайн сейчас неверно. По всей видимости, проблема в условии `first_digit > 8`. Из-за этого дизайн уходит в ЕЕ на 64. Кроме того, когда я говорил про счетчик, я не имел в виду заводить специальный счетчик для отсчета до сброса.  
Возьмите вашу базовую часть. Там уже есть счетчик, который считает как надо, обновите дизайн первой частью индивидуального задания, чтоб дизайн срабатывал по отжатию. А теперь следите за руками:
Сейчас у ваш дизайн выводит счетчик в шестнадцатиричном виде. От вас просят сделать вывод в десятичном. И чтобы после 99 выводилось ЕЕ. Всё. Подумайте, как с помощью нехитрой математики получить десятки и единицы числа, и что еще нужно сделать, чтобы после 99 на хексы шло ЕЕ. Больше ничего и не надо, счетчик сам будет переполняться и обнуляться.

2020-05-13 07:00 UTC, HepoH3 requested changes
В остальном дизайн полностью рабочий. Запушьте последнее изменение и лаба сдана.

2020-05-13 07:00 UTC, HepoH3 commented on lab2/rtl/counter.v
> +            second_digit <= ( hex_counter % 8'd100 ) / 4'd10;
Вы находитесь в блоке `else` условия `hex_counter > 99` , операция `hex_counter % 100` здесь излишняя.

2020-05-13 10:12 UTC, HepoH3 approved these changes

2020-05-13 10:12 UTC, merged