lab2_fix
HepoH3/MIET_FPGA_practicum pull request #74
Opened 2020-05-12 11:31 UTC by Niheim

# Публикуя данный пул-реквест, я гарантирую, что:
1) Я предлагаю к слиянию только файлы с hdl-описанием разрабатываемого вами устройства, а так же тестбенчи для его тестирования. Исключением могут разве что быть (но не обязаны) файлы .gitignore, и файлы констрейнов (.xdc), tcl-скрипты для сборки проекта.
2) Мной не были удалены исходные файлы репозитория;
3) Мной реализовано устройство в соответствии с данным в исходном репозитории прототипом. Таким образом, любой человек, зная исходный файл репозитория сможет подключить моё устройство к своему проекту и все соберётся.
4) Мой код соответствует [кодстайлу](http://82.179.184.185:82/doku.php?id=verilog_guideline);
5) Коммиты в публикуемом мной пулл-реквесте являются [содержательными](https://habr.com/ru/post/416887/);  
6) Перед отправкой пул-реквеста я убедился, что мой проект собирается, и проведя собственные тесты оказался удовлетворён его работой.

2020-05-12 12:24 UTC, frarrr requested changes

2020-05-12 12:24 UTC, frarrr commented on lab2/rtl/counter.v
> +  assign key_i_0_was_pressed = ~key_i_0_syncroniser[2] & key_i_0_syncroniser[1];
Операция `assign` применима только для типа `wire`

2020-05-12 12:24 UTC, frarrr commented on lab2/rtl/counter.v
> +    key_i_0_syncroniser[2] <= key_i_0_syncroniser[1];
Здесь вы объявляете модуль без ресета

2020-05-12 12:24 UTC, frarrr commented on lab2/rtl/counter.v
> +  assign key_i_0_was_pressed = ~key_i_0_syncroniser[2] & key_i_0_syncroniser[1];
Кажется что этот блок в целом нигде не используется

2020-05-12 12:24 UTC, frarrr commented on lab2/rtl/counter.v
> +    case (sw_i [3:0])
Не забывайте ставить пробелы между скобками и их содержимым

2020-05-12 12:24 UTC, frarrr commented on lab2/rtl/counter.v
> +  end
Для повышения читаемости лучше перенести присваивание на следующую строчку

2020-05-12 12:24 UTC, frarrr commented on lab2/rtl/counter.v
> +    end
Модуль без ресета

2020-05-12 12:24 UTC, frarrr commented on lab2/rtl/counter.v
> +    end
Для отступов также стоит использовать 2 пробела, а не 4

2020-05-12 12:24 UTC, frarrr commented on lab2/rtl/counter.v
> +    end
Не забудьте пробелы вокруг скобок

2020-05-12 15:32 UTC, Niheim commented
Обновлено

2020-05-13 11:07 UTC, frarrr requested changes
Еще в одном месте не добавлены пробелы, в предыдущем ревью упоминалось

2020-05-13 11:07 UTC, frarrr commented on lab2/rtl/counter.v
> +  end
Значения в регистр тоже должны записываться по нажатию кнопки

2020-05-13 11:07 UTC, frarrr commented on lab2/rtl/counter.v
> +  end
Добавьте ресет в модуль

2020-05-13 11:07 UTC, frarrr commented on lab2/rtl/counter.v
> +    case (sw_i [3:0])
Здесь вам нужно присваивать значение в зависимости от содержимого счетчика, а не переключателей

2020-05-13 11:47 UTC, frarrr requested changes

2020-05-13 11:47 UTC, frarrr commented on lab2/rtl/counter.v
> +  end
Нет условия ресета

2020-05-13 11:58 UTC, Niheim commented
Зачем там ресет?

2020-05-13 12:33 UTC, frarrr commented
> Зачем там ресет?

Вообще на странице с кодстайлом написано, что модули без ресета создавать нельзя. Но основные причины в том, что без ресета в начальный момент времени регистры имеют неопределенное значение и это может вызвать некорректное поведение модуля после снятия ресета. Для ПЛИС первая проблема имеет не такое большое значение как для ASIC, но все еще использование ресета в синхронных блоках -- хорошая и безопасная практика. Иногда его не используют намеренно, но по умолчанию для избежания ошибок стоит прописывать условие сброса

2020-05-13 13:19 UTC, Niheim commented
Так?

2020-05-13 13:59 UTC, frarrr requested changes

2020-05-13 13:59 UTC, frarrr commented on lab2/rtl/counter.v
> +      btn_sync[2:0] = 3'b0;
Здесь нужно неблокирующее присваивание, vivado выдает предупреждение на этот счет

2020-05-13 14:15 UTC, Niheim commented
Поставил неблокирующее

2020-05-13 15:18 UTC, frarrr commented
Принято

2020-05-13 15:18 UTC, merged