Lab2 Bezborodov Individual Task
HepoH3/MIET_FPGA_practicum pull request #75
Opened 2020-05-12 12:49 UTC by somenewacc

# Публикуя данный пул-реквест, я гарантирую, что:
1) Я предлагаю к слиянию только файлы с hdl-описанием разрабатываемого вами устройства, а так же тестбенчи для его тестирования. Исключением могут разве что быть (но не обязаны) файлы .gitignore, и файлы констрейнов (.xdc), tcl-скрипты для сборки проекта.
2) Мной не были удалены исходные файлы репозитория;
3) Мной реализовано устройство в соответствии с данным в исходном репозитории прототипом. Таким образом, любой человек, зная исходный файл репозитория сможет подключить моё устройство к своему проекту и все соберётся.
4) Мой код соответствует [кодстайлу](http://82.179.184.185:82/doku.php?id=verilog_guideline);
5) Коммиты в публикуемом мной пулл-реквесте являются [содержательными](https://habr.com/ru/post/416887/);  
6) Перед отправкой пул-реквеста я убедился, что мой проект собирается, и проведя собственные тесты оказался удовлетворён его работой.

Задания:
6) При выводе значение на sw  выделить крайний справа нулевой бит. 10100111 => 00001000
6) Реализовать два счетчика. Один увеличивается другой уменьшается. Значение выводится на hex0 hex1. sw[11] = 0 выводится счетчик с увеличением. Sw[11] = 1 выводится счетчик с уменьшением.

2020-05-13 11:43 UTC, frarrr requested changes

2020-05-13 11:43 UTC, frarrr commented on lab2/rtl/counter.v
> +reg  [7:0] counter1;
Возможно стоит подобрать более подходящие названия регистров, по этим не очевидно какой из счетчиков какой

2020-05-13 11:43 UTC, frarrr commented on lab2/rtl/counter.v
> +        counter1 <= ~counter1;
Не обязательно здесь прописывать условия для `counter` и `counter1`, они выполнятся в любом случае при переполнении, если разрядности верные.

2020-05-13 11:43 UTC, frarrr commented on lab2/rtl/counter.v
> +end
Здесь вы описываете комбинационную логику, поэтому присваивание нужно использовать блокирующее. Но еще лучше использовать тернарный оператор `assign a = b ? c : d`

2020-05-13 11:43 UTC, frarrr commented on lab2/rtl/counter.v
> +  .out(hex1_o    ));
Поправьте выравнивание и пробелы

2020-05-13 11:43 UTC, frarrr commented on lab2/rtl/counter.v
>  assign ledr_o = q;
Вам нужно изменить вывод значений на ledr_o так, как сказано в индивидуальном задании. То есть не так же как раньше передавать значение с переключателей, а изменить его с выделением нулевого бита

2020-05-13 11:43 UTC, frarrr commented on lab2/rtl/counter.v
> +reg  [0:0]  event_pass;
`[0:0]`-- точно лишняя запись

2020-05-13 12:49 UTC, frarrr requested changes

2020-05-13 12:49 UTC, frarrr commented on lab2/rtl/counter.v
> +end
Неет, проводам не присваиваются значения в блоке always. Странно, если vivado вас об этом не предупредил

2020-05-13 12:49 UTC, frarrr commented on lab2/rtl/counter.v
> +end
Тем более что у вас switch объявлен как регистр, тогда к нему нельзя применять ключевое слово assign. Выберите здесь что-то одно

2020-05-13 12:52 UTC, frarrr commented
У вас, кстати, файлы проекта лежат в репозитории, удалите их, пожалуйста

2020-05-13 12:53 UTC, somenewacc commented on lab2/rtl/counter.v
> +end
Извиняюсь, не доглядел что-то.

2020-05-13 13:46 UTC, frarrr requested changes

2020-05-13 13:46 UTC, frarrr commented on lab2/rtl/counter.v
> +end
Конструкция, которую вы описали для детектирования нуля в регистре симулируется верно, но не синтезируется. Вероятнее всего, САПР не может понять как представить этот блок always в виде простых логических элементов. Попробуйте переписать логику и убедитесь, что дизайн проходит синтез без ошибок или предупреждений на счет этого блока always

2020-05-13 15:33 UTC, frarrr requested changes
Хорошая схема, но опять же, про присваивание значения регистру в разных блоках always синтезатор вас должен был предупредить

2020-05-13 15:33 UTC, frarrr commented on lab2/rtl/counter.v
> +    sw_event           <= 10'b0;
Забыли удалить, видимо

2020-05-13 15:35 UTC, frarrr commented on lab2/rtl/counter.v
> +    sw_event           <= 10'b0;
Хотя на самом деле, все равно нужно ledr_o обновлять по нажатию

2020-05-13 16:00 UTC, frarrr commented
> Хотя на самом деле, все равно нужно ledr_o обновлять по нажатию

Имелось в виду то, что вы в основной части обновляли `ledr_o` по нажатию на key[0], а в индивидуальном задании от этого избавились

2020-05-13 16:05 UTC, somenewacc commented
Да, так как Александр Силантьев мне написал, что я должен формировать из регистра значения на ledr непрерывно, поэтому я и убрал запись в ledr при нажатии кнопки.

2020-05-13 16:06 UTC, frarrr commented
Хм, тогда уточню сейчас вопрос, подождите пожалуйста

2020-05-13 16:14 UTC, somenewacc commented
Вообще обновлять ```ledr_o``` по нажатию ```key_i[0]``` даже легче, так что добавить это не трудно.

2020-05-13 16:16 UTC, frarrr commented
В любом случае давайте подождем, чтобы у всех потом было одинаково

2020-05-14 08:22 UTC, frarrr commented
Все-таки нужно по нажатию обновлять ledr_o, но непрерывно делать преобразование

2020-05-14 08:26 UTC, somenewacc commented
Получается я себе усложнил задачу?
Хорошо, исправил.

2020-05-14 08:46 UTC, frarrr commented
Принято

2020-05-14 08:46 UTC, merged