Vt23 Shokiri individual task 1-8 (Lab2)
HepoH3/MIET_FPGA_practicum pull request #76
Opened 2020-05-12 13:22 UTC by Lipkoffsky

# Публикуя данный пул-реквест, я гарантирую, что:
1) Я предлагаю к слиянию только файлы с hdl-описанием разрабатываемого вами устройства, а так же тестбенчи для его тестирования. Исключением могут разве что быть (но не обязаны) файлы .gitignore, и файлы констрейнов (.xdc), tcl-скрипты для сборки проекта.
2) Мной не были удалены исходные файлы репозитория;
3) Мной реализовано устройство в соответствии с данным в исходном репозитории прототипом. Таким образом, любой человек, зная исходный файл репозитория сможет подключить моё устройство к своему проекту и все соберётся.
4) Мой код соответствует [кодстайлу](http://82.179.184.185:82/doku.php?id=verilog_guideline);
5) Коммиты в публикуемом мной пулл-реквесте являются [содержательными](https://habr.com/ru/post/416887/);  
6) Перед отправкой пул-реквеста я убедился, что мой проект собирается, и проведя собственные тесты оказался удовлетворён его работой.

2020-05-12 13:30 UTC, Lipkoffsky commented
Кажется я не правильно понял задание.
Нужно, чтобы числа от 0 до 99 на hex0 и hex1 выводились цифрами от 0 до 9?

2020-05-12 13:40 UTC, frarrr commented
>Кажется я не правильно понял задание.
>Нужно, чтобы числа от 0 до 99 на hex0 и hex1 выводились цифрами от 0 до 9?

Да, именно, в десятичном виде

2020-05-12 14:27 UTC, Lipkoffsky commented
Исправил
теперь вывод идет от 0 до 9

2020-05-13 12:42 UTC, frarrr requested changes

2020-05-13 12:42 UTC, frarrr commented on lab2/rtl/Debounce.v
> +    if ( rst_i)
Верните сюда пробел возле скобки

2020-05-13 12:42 UTC, frarrr commented on lab2/rtl/counter.v
> +      if ( counter > 'd99) out_of_range <= 1'b1;
Кажется что `out_of_range` можно сделать проводом, это немного, но облегчит always блок

2020-05-13 12:42 UTC, frarrr commented on lab2/rtl/counter.v
> +        hex1 = 'd14;
Здесь нужно другое присваивание

2020-05-13 12:42 UTC, frarrr commented on lab2/rtl/dec_counter.v
> +  reg        out_of_range;
Кажется что это ненужный файл

2020-05-13 12:42 UTC, frarrr commented on lab2/rtl/counter.v
>    .data_i       ( sw_i         ),
Здесь вы передаете в модули `!key_i[1]` в качестве ресета. Внутри модуля вы описываете условие сброса как `if ( rstn_i )`. Тогда подумайте, нужно вам использовать `negedge rstn_i` или `posedge rstn_i`

2020-05-13 12:42 UTC, frarrr commented on lab2/rtl/register.v
>      else if ( en_i)
И здесь тоже скобки и пробелы

2020-05-13 12:58 UTC, Lipkoffsky commented on lab2/rtl/counter.v
> +        hex1 = 'd14;
в смысле через <= ?

2020-05-13 13:48 UTC, Lipkoffsky commented on lab2/rtl/counter.v
> +      if ( counter > 'd99) out_of_range <= 1'b1;
Он в принципе не нужен

2020-05-13 13:50 UTC, Lipkoffsky commented on lab2/rtl/counter.v
> +      if ( counter > 'd99) out_of_range <= 1'b1;
Исправил

2020-05-13 14:04 UTC, frarrr commented on lab2/rtl/counter.v
> +        hex1 = 'd14;
Да, внутри одного блока always присваивания должны быть одинаковые, но вижу вы уже исправили

2020-05-13 15:15 UTC, frarrr requested changes

2020-05-13 15:15 UTC, frarrr commented on lab2/rtl/counter.v
> +          end
Когда счетчик становится равен 100, на hex появляется A0 и только после следующего нажатия -- EE

2020-05-13 16:37 UTC, Lipkoffsky commented on lab2/rtl/counter.v
> +          end
исправил условие на (counter == 99)

2020-05-13 16:56 UTC, frarrr commented
Принято

2020-05-13 16:56 UTC, merged