lab2_individual_task
HepoH3/MIET_FPGA_practicum pull request #79
Opened 2020-05-12 17:24 UTC by capython59

# Публикуя данный пул-реквест, я гарантирую, что:
1) Я предлагаю к слиянию только файлы с hdl-описанием разрабатываемого вами устройства, а так же тестбенчи для его тестирования. Исключением могут разве что быть (но не обязаны) файлы .gitignore, и файлы констрейнов (.xdc), tcl-скрипты для сборки проекта.
2) Мной не были удалены исходные файлы репозитория;
3) Мной реализовано устройство в соответствии с данным в исходном репозитории прототипом. Таким образом, любой человек, зная исходный файл репозитория сможет подключить моё устройство к своему проекту и все соберётся.
4) Мой код соответствует [кодстайлу](http://82.179.184.185:82/doku.php?id=verilog_guideline);
5) Коммиты в публикуемом мной пулл-реквесте являются [содержательными](https://habr.com/ru/post/416887/);  
6) Перед отправкой пул-реквеста я убедился, что мой проект собирается, и проведя собственные тесты оказался удовлетворён его работой.

Требовалось выполнить задания 4 и 3:
4) При выводе значение на sw обнулить крайний справа единичный бит. 01011000 => 01010000
3) Счетчик 16 разрядный. Выводить его значение на 4 семи-сегментных индикатора

2020-05-13 16:58 UTC, capython59 commented
Должно все работать

2020-05-14 08:13 UTC, frarrr requested changes

2020-05-14 08:13 UTC, frarrr commented on lab2/rtl/hex.v
> +  case (in)
Нужны пробелы между скобками и их содержимым

2020-05-14 08:13 UTC, frarrr commented on lab2/rtl/counter.v
> +wire  [6:0]      hex3_d;
Эти провода не нужны

2020-05-14 08:13 UTC, frarrr commented on lab2/rtl/counter.v
>    end
Добавьте асинхронный ресет в модуль

2020-05-14 08:13 UTC, frarrr commented on lab2/rtl/counter.v
> +        counter  <= 10'd0;
Разрядность counter больше 10

2020-05-14 09:28 UTC, frarrr commented
Принято

2020-05-14 09:28 UTC, merged

2020-05-14 09:32 UTC, frarrr commented
Постарайтесь только в следующий раз сразу проверять код на ресеты, кодстайл и прочее. Эти исправления плюс-минус несущественные только в этой лабе, и количество исправлений индивидуального задания тоже влияет на балл