Individual Task Ivolga Oleg
HepoH3/MIET_FPGA_practicum pull request #81
Opened 2020-05-12 19:35 UTC by M4RKERGit

# Публикуя данный пул-реквест, я гарантирую, что:
1) Я предлагаю к слиянию только файлы с hdl-описанием разрабатываемого вами устройства, а так же тестбенчи для его тестирования. Исключением могут разве что быть (но не обязаны) файлы .gitignore, и файлы констрейнов (.xdc), tcl-скрипты для сборки проекта.
2) Мной не были удалены исходные файлы репозитория;
3) Мной реализовано устройство в соответствии с данным в исходном репозитории прототипом. Таким образом, любой человек, зная исходный файл репозитория сможет подключить моё устройство к своему проекту и все соберётся.
4) Мой код соответствует [кодстайлу](http://82.179.184.185:82/doku.php?id=verilog_guideline);
5) Коммиты в публикуемом мной пулл-реквесте являются [содержательными](https://habr.com/ru/post/416887/);  
6) Перед отправкой пул-реквеста я убедился, что мой проект собирается, и проведя собственные тесты оказался удовлетворён его работой.

2020-05-14 10:30 UTC, frarrr requested changes

2020-05-14 10:30 UTC, frarrr commented on lab2/rtl/counter.v
> +end
В порядке значимости:
1) У меня синтез выдал 90 критических предупреждений -- либо вы не синтезировали дизайн, либо не обратили на них внимание, либо у нас с вами разные САПР. В любом случае это плохо, но отпишите если ваш синтез не показал ничего подозрительного
2) Нельзя присваивать значения одним регистрам в разных блоках always
3) В блоке комбинационной логики у вас используется неблокирующее присваивание
4) В условиях вроде `( cnt2 < 8'hFF )` нет смысла -- они выполнятся сами собой при переполнении, если вы правильно указали разрядность счетчика
5) `ind_out` нужно выбирать либо в комбинационной схеме (в верным присваиванием), либо сделать его проводом, чтобы не получать ненужную задержку в один такт
6) `cnt1` и `cnt2` -- не самые лучшие названия, из них непонятно, какой счетчик считает вверх, а какой -- вниз

2020-05-14 10:59 UTC, M4RKERGit commented on lab2/rtl/counter.v
> +end
1) Использую Vivado 2019.2, попробовал синтезировать, выявилась только одна ошибка(раньше не синтезировал по той причине, что слишком маломощный пк, синтез занимает минут 8 иногда). Ошибка заключается в 
always @( posedge clk100_i or negedge key_i[1] ) begin
этой строчке, ему не нравится использование posedge и negedge одновременно, насколько я понял)
2)Это был "костыль", ибо у меня по непонятным причинам крашилась симуляция на 220 нс, в этот момент посылался сигнал bt_down, но сейчас смог поправить, вроде получается.

Разбираю остальные ошибки

2020-05-14 11:03 UTC, frarrr commented on lab2/rtl/counter.v
> +end
1. У меня та же версия вивадо и после пересборки проекта ошибки сохраняются, но спишем это на магию. Но вы неверно поняли ошибку, использование posedge и negedge ничем не запрещается, даже наоборот очень распространего. Скорее всего проблема в пунктах 2 и 3

2020-05-14 11:32 UTC, M4RKERGit commented on lab2/rtl/counter.v
> +end
Исправил ошибки 2 и 3, но ошибка при синтезе осталась. Апдейтнул реквест

2020-05-14 12:07 UTC, frarrr commented on lab2/rtl/counter.v
> +end
Синтез с ошибками не проверяется. Но попробуйте проверить, все ли у вас правильно с `if-else`. Заодно проверьте, что у вас правильно используются отступы

2020-05-14 12:22 UTC, M4RKERGit commented on lab2/rtl/counter.v
> +end
Я сейчас сравниваю с другими работами, что уже приняты, у них такое же построение. Иностранные форумы говорят, что надо разделить этот always на два идентичных, но в одном сделать posedge clk, а в другом negedge key_i.

2020-05-14 12:27 UTC, frarrr commented on lab2/rtl/counter.v
> +end
То есть вы уверены в том, что в вашем новом блоке `always` нет ошибок `if-else`?

2020-05-14 12:34 UTC, M4RKERGit commented on lab2/rtl/counter.v
> +end
Тысяча извинений, ошибка была в том, что end стоял не в той строчке, что надо. Исправил, теперь синтез проходит без проблем

2020-05-14 13:29 UTC, frarrr requested changes

2020-05-14 13:29 UTC, frarrr commented on lab2/rtl/counter.v
> +end
Нужно поправить отступы

2020-05-14 13:29 UTC, frarrr commented on lab2/rtl/ccccounter.v
> + .out ( hex0_o       ));
Эти модули уже вызваны в модуле counter

2020-05-14 13:29 UTC, frarrr commented on lab2/rtl/counter.v
> +( .sw_i       ( sw_i      ),
Размерности входного сигнала sw_i и выходного sw_i не совпадают

2020-05-14 13:43 UTC, M4RKERGit commented on lab2/rtl/ccccounter.v
> + .out ( hex0_o       ));
То есть, их можно отсюда смело убирать из ccccounter, чтобы с hex работал только counter, в котором индивидуальное задание?

2020-05-14 14:23 UTC, M4RKERGit commented on lab2/rtl/ccccounter.v
> + .out ( hex0_o       ));
Вроде как понял, коммит закинул

2020-05-15 11:10 UTC, frarrr requested changes

2020-05-15 11:10 UTC, frarrr commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
`hex1_o` и `hex0_o` выводятся одновременно из модулей thirdmod, ind1, ind0.
Из `ccccounter` стоит удалить ненужные выводы

2020-05-15 11:10 UTC, frarrr commented on lab2/rtl/counter.v
> +      if ( indc==3 ) begin
Добавьте здесь пробелы вокруг оператора `==`

2020-05-15 11:10 UTC, frarrr commented on lab2/rtl/counter.v
> +  end
Для этого куска кода все еще не исправлены пробелы

2020-05-15 12:30 UTC, M4RKERGit commented on lab2/rtl/counter.v
> +  end
Всё исправил, коммит залил

2020-05-15 13:19 UTC, frarrr requested changes

2020-05-15 13:19 UTC, frarrr commented on lab2/rtl/counter.v
> +    indc <= indc + 1;
Не исправлены пробелы

2020-05-15 13:19 UTC, frarrr commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
Теперь этот модуль не нужен, судя по всему, так как у него нет выходов. Vivado после синтеза тоже предупреждает, что модуль не будет синтезирован и удалится автоматически.

2020-05-15 13:19 UTC, frarrr commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
Обратите также внимание на то, что светодиоды у вас обновляются каждое нажатие. На самом деле они как и семисегментники должны меняться после трех нажатий

2020-05-15 13:48 UTC, M4RKERGit commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
Тогда его можно удалить из проекта?

2020-05-15 14:05 UTC, M4RKERGit commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
Несколько коммитов назад у меня была реализована именно такая схема, с проверкой на 3 нажатия, сейчас верну её на место, просто не точно понял задание, извините

2020-05-15 14:10 UTC, M4RKERGit commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
Если вовзращать такую схему с блокирующим присваиванием, вивадо не позволяет это сделать, так как ind_out теперь wire, как вы просили в одном ревью, так что я в тупике
![image](https://user-images.githubusercontent.com/62885141/82059579-e3f2f000-96ce-11ea-8bec-8da1ce83b136.png)

2020-05-15 15:19 UTC, frarrr commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
Не вижу смысла возвращать эту схему, поэтому непонятно, где здесь тупик
Это индивидуальное задание, вы должны сами решать, какая структура должна быть у вашего дизайна и как реализовать логику, которая решает задачу.

2020-05-15 15:31 UTC, M4RKERGit commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
Проблема в том, что я не могу присвоить что-либо wire в цикле. Поэтому либо снова делать ind_out типа reg, либо обновлять каждое нажатие, как сейчас. Второй вариант, безусловно, расходится с заданием, но и первый вариант вы отторгли несколько коммитов назад. 
![image](https://user-images.githubusercontent.com/62885141/82067847-ec9cf380-96d9-11ea-8a4d-9f965b69a4ef.png)
Я просто не знаю, как можно обойти это замечание: оставить wire, но при этом сделать обновление вывода каждые три нажатия.
Я пытался посмотреть работы коллег, но у них реализовано это так же, как у меня на данный момент, через assign, и работа при этом засчитана. Поэтому я в тупике, скорее всего в силу нехватки знаний.

2020-05-15 15:32 UTC, M4RKERGit commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
Пока что кину коммит с отключённым модулем и фиксом кодстайла

2020-05-15 15:54 UTC, frarrr commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
Вы точно уверены, что поняли суть проблемы? `ind_out` никаким образом не участвует в том, что описано в первом комментарии

2020-05-15 16:00 UTC, M4RKERGit commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
ind_out сообщается на вход dec_hex, потом отображается на "дисплее" платы, по идее, надо контролировать обновление ind_out. Могу конечно ошибаться, но у меня уже мозги плывут.

2020-05-15 16:03 UTC, M4RKERGit commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
Ещё я не совсем, может быть, понял задание изначально, потому что допустил, что можно будет между тремя нажатиями key0 поменять sw11, чтобы взглянуть на значения другого счётчика, показалось довольно практичным). Но если суть именно в том, что строго каждые три нажатия, то буду думать

2020-05-15 16:07 UTC, frarrr commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
> Обратите также внимание на то, что светодиоды у вас обновляются каждое нажатие.

Светодиоды -- это ledr. Они у вас по кнопке каждое нажатие меняются. А нужно через 3.
В любом случае, если у вас "мозги плывут", то лучше сделать перерыв, а не делать много попыток сдачи, особенно с учётом того что они учитываются в итоговом балле. Проверьте лишний раз на стимуляции, что все работает точно по заданию

2020-05-15 16:09 UTC, frarrr commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
Пока трех нажатий нет, значение на sw игнорируется, а когда третье происходит, то выставляется текущее
В любом случае, если есть сомнения в трактовке задания, спрашивайте

2020-05-15 16:10 UTC, M4RKERGit commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
Но ledr же никак не учавствуют в моём индивидуальном задании, они являются частью общего задания в лабе, почему они тоже должны меняться на 3 нажатие? И да, прошу прощения, перепутал светодиоды и hex

2020-05-15 16:15 UTC, frarrr commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
В задании сказано, что после трех нажатий на key[0] происходит событие. В основном задании под событием понималось нажатие на кнопку. По событию менялись светодиоды и 7-сегментники. Теперь это событие заменяется на другое из задания.

2020-05-15 16:17 UTC, M4RKERGit commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
Я только что прозрел... Сейчас попытаюсь исправить. Надо же в модуль regtoledr добавить точно такой же счётчик, инкрементируемый при нажатии на key0?

2020-05-15 16:20 UTC, frarrr commented on lab2/rtl/counter.v
> +  .clk100_i   ( clk100_i  ));
Опять же, это индивидуальное задание, решение как и что делать принимаете вы.
Но если вы увеличите аппаратные затраты дизайна, когда можно очевидным образом этого избежать, то я попрошу вас опять переделать. Исправление можно в две строчки буквально сделать

2020-05-15 17:25 UTC, M4RKERGit commented
Добавил ещё один коммит, перегнал всё в один модуль, теперь должно работать

2020-05-16 13:54 UTC, HepoH3 commented
Так, Дарья пока не может проверить ваш дизайн, поэтому попросила меня провести ревью.
У вас сейчас что-то странное происходит, смотрим на времянку:  
![](https://puu.sh/FL9va/76164f3af7.png)  
Реакция дизайна должна происходить на каждое третье нажатие. Я отметил зелеными линиями, когда она должна была быть. Красными линиями выделены моменты, когда среагировал ваш дизайн. Как видите, он не просто реагирует на одно нажатие позже, он вообще очень непредсказуемо себя ведет, в какой-то момент значения семисегментников изменяются до изменения счетчика, хотя это все должно происходить синхронно.  
Я вам крайне рекомендую погонять тесты своего дизайна и посмотреть на симуляцию.

2020-05-16 13:55 UTC, HepoH3 requested changes
Так, Дарья пока не может проверить ваш дизайн, поэтому попросила меня провести ревью.
У вас сейчас что-то странное происходит, смотрим на времянку:  
![](https://puu.sh/FL9va/76164f3af7.png)  
Реакция дизайна должна происходить на каждое третье нажатие. Я отметил зелеными линиями, когда она должна была быть. Красными линиями выделены моменты, когда среагировал ваш дизайн. Как видите, он не просто реагирует на одно нажатие позже, он вообще очень непредсказуемо себя ведет, в какой-то момент значения семисегментников изменяются до изменения счетчика, хотя это все должно происходить синхронно.  
Я вам крайне рекомендую погонять тесты своего дизайна и посмотреть на симуляцию.

2020-05-16 14:46 UTC, M4RKERGit commented
Да, в силу самопального ТБ подобного не заметил, сейчас переделал, вроде всё синхронно и не сбивается

2020-05-16 15:40 UTC, HepoH3 commented
>
> Коммит залит
> 
Для первой лабы так уж и быть, проигнорирую, но в следующих приучите себя работать с гитом. Вот все эти ваши заливки и удаления файлов из браузера — совсем не круто. Тоже самое касается сообщений к коммитам. В дальнейших лабах за это буду по рукам бить.  
>
> инкрементация счётчика и проверка этого условия с последующими действиями проходили параллельно, что не есть хорошо, теперь они последовательно идут
>
Вот в этой части мне прямо любопытно послушать, что вы понимаете под "последовательно" и "параллельно" при описании аппаратуры. Не буду вас больше мучить этим пул-реквестом, но я бы посоветовал вам перечитать мат.часть.

2020-05-16 15:40 UTC, HepoH3 approved these changes

2020-05-16 15:40 UTC, merged