lab2 Shakyrianova individual part
HepoH3/MIET_FPGA_practicum pull request #82
Opened 2020-05-12 19:44 UTC by Mercunus

# Публикуя данный пул-реквест, я гарантирую, что:
1) Я предлагаю к слиянию только файлы с hdl-описанием разрабатываемого вами устройства, а так же тестбенчи для его тестирования. Исключением могут разве что быть (но не обязаны) файлы .gitignore, и файлы констрейнов (.xdc), tcl-скрипты для сборки проекта.
2) Мной не были удалены исходные файлы репозитория;
3) Мной реализовано устройство в соответствии с данным в исходном репозитории прототипом. Таким образом, любой человек, зная исходный файл репозитория сможет подключить моё устройство к своему проекту и все соберётся.
4) Мой код соответствует [кодстайлу](http://82.179.184.185:82/doku.php?id=verilog_guideline);
5) Коммиты в публикуемом мной пулл-реквесте являются [содержательными](https://habr.com/ru/post/416887/);  
6) Перед отправкой пул-реквеста я убедился, что мой проект собирается, и проведя собственные тесты оказался удовлетворён его работой.

Задания:
8) Событие происходит если сначала была нажата кнопа key[0] а потом key[2]. Наоборот не работает.
3) Счетчик 16 разрядный. Выводить его значение на 4 семи-сегментных индикатора.

2020-05-14 12:59 UTC, frarrr requested changes

2020-05-14 12:59 UTC, frarrr commented on lab2/rtl/counter.v
>  end
Из-за этих строчек у меня после синтеза генерируется 75 критических предупреждений и еще сколько-то обычных. Напишите, если ваша версия vivado ничего не выдает в ответ на них.

Проблемы здесь следующие:
1) В разных блоках always нельзя присваивать значение одним и тем же регистрам. В каком блоке регистры используются, в том -- и сбрасываются.
2) В блоке комбинационной логики у вас используется неблокирующее присваивание.
3) Кажется что в ситуации, когда key0 была нажата и отпущена, а затем была нажата key2, счетчик у вас инкрементируется. Нужно сделать так, чтобы он увеличивался когда обе кнопки нажаты, но последней была нажата key2

2020-05-14 12:59 UTC, frarrr commented on lab2/rtl/dec_hex.v
>    case (in)
Здесь нужны пробелы вокруг `in`

2020-05-14 14:57 UTC, Mercunus commented on lab2/rtl/counter.v
>  end
Какая должна быть задержка между нажатиями key0 и key2? Из-за debouncer'а сигнал нажатий все равно сгенерируется одновременно.

2020-05-14 16:03 UTC, frarrr commented on lab2/rtl/counter.v
>  end
> Из-за debouncer'а сигнал нажатий все равно сгенерируется одновременно.

Не особо понятно что вы имеете в виду. Если в разное время нажать key0 и key2, то в разное время появятся key0_pressed и key2_pressed. Если обе кнопки нажаты в течение одного такта, вы должны игнорировать это событие, то key0_pressed и key2_pressed будут одинаковыми и вы это событие должны игнорировать

2020-05-15 08:04 UTC, frarrr requested changes

2020-05-15 08:04 UTC, frarrr commented on lab2/rtl/counter.v
> +        switch  <= 1'b0;
Все еще возможна ситуация, когда нажата только key2, а key0 уже не отпущена, и событие засчитается.
Нужно обрабатывать только событие, когда key0 уже нажата и key2 нажимается сейчас

2020-05-15 09:00 UTC, Mercunus commented on lab2/rtl/counter.v
> +        switch  <= 1'b0;
Возможно вы имели в виду что key0 уже отпущена? Не совсем пойму что вы имеете в виду. При одновременном нажатии или при разнице в нажатии меньше чем такт, то счетчик не инкрементируется. Если разница между нажатиями больше такта

2020-05-15 10:26 UTC, frarrr commented on lab2/rtl/counter.v
> +        switch  <= 1'b0;
Да, прошу прощения, конечно когда key0 уже отпущена

2020-05-15 11:23 UTC, frarrr commented
Все еще не решена проблема.
Представьте, что вы нажимаете на key0, отпускаете ее и ждете некоторое время. Затем вы нажимаете на key2. Судя по вашему коду, это приведет к увеличению счетчика. По заданию же нужно чтобы обе кнопки были нажаты.

2020-05-15 11:49 UTC, Mercunus commented
Вроде сделала чтобы обрабатывало нажатия через такт

2020-05-15 11:58 UTC, frarrr commented
А если вы держите key0 дольше одного такта прежде чем нажать на key2?

2020-05-15 11:59 UTC, frarrr requested changes

2020-05-15 11:59 UTC, frarrr commented on lab2/rtl/counter.v
> +      switch <= key0_pressed;
Если вы попадаете в этот `if`, то `key0_pressed` в любом случае равен 1

2020-05-15 12:00 UTC, Mercunus commented
Так из-за debouncer'а удержание регистрироваться не будет. На key0_pressed поступит сигнал только на 1 такт.

2020-05-15 12:04 UTC, frarrr commented
> Так из-за debouncer'а удержание регистрироваться не будет. На key0_pressed поступит сигнал только на 1 такт.

Да, в этом и проблема вашей реализации. В задании буквально написано следующее:
"Событие происходит если сначала была нажата кнопа key[0] а потом key[2]. Наоборот не работает."
Здесь не говорится, что если вы удерживаете key[0] один такт, то событие происходит, а если два такта -- нет. Вам нужно перекрыть все случаи

2020-05-15 13:04 UTC, frarrr commented
Нашла как минимум одну ситуацию, когда происходит ложное срабатывание, и еще одну -- когда срабатывание должно быть, но не происходит.
Попробуйте рассмотреть больше комбинаций нажатия key0 и key2, когда симулируете свой дизайн.

2020-05-15 14:16 UTC, Mercunus commented
Вроде исправила пару ложных срабатываний

2020-05-15 15:39 UTC, frarrr commented
Вот пример ситуации, когда обе кнопки не нажаты одновременно, но срабатывание происходит:

![изображение](https://user-images.githubusercontent.com/24639645/82068922-4fdb5580-96db-11ea-9937-671811c2dccd.png)

2020-05-15 16:03 UTC, Mercunus commented
Вроде исправила данный нюанс

2020-05-15 16:34 UTC, frarrr commented
Принято

2020-05-15 16:35 UTC, merged

2020-05-15 17:26 UTC, Mercunus commented
> Принято

можете рассказать, почему работа оценена 2 баллами?

2020-05-15 17:55 UTC, frarrr commented
> можете рассказать, почему работа оценена 2 баллами?

Да, без проблем

1) Непредвиденные ошибки синтеза, в том числе критические. Если вы их видите -- дизайн точно не стоит отправлять на ревью
2) Вы не поняли задание в первый раз -- это нормально, так как мы описали его так, что возможны разночтения. Но если вторая и третья проверка выявила ту же ошибку, то это уже минус. 
3) Исправления, которые могли бы быть проверены симуляцией разных положений key[0] и key[2] перед отправкой. На мой взгляд описанные тесткейсы можно предусмотреть в тестбенче.
4) Использование неблокирующих присваиваний в блоке комбинационной логики. На странице о верилоге в вики об этом говорится, это значительная ошибка. Как и использование разных типов присваиваний в один регистр в разных блоках always.
5) Кодстайл и мелкие недочеты почти не учитывались. В следующих лабах на них больше будет обращаться внимания.
6) Оценивалась в основном индивидуальная часть по понятным, думаю, причинам. Основная часть значима только если вы повторяете недочеты из нее, у вас их почти не было и они касались кодстайла.

Первые 4 пункта мной оценивались как -1, но 2 балла из 5 уже достаточно мало
Надеюсь ответила на вопрос

2020-05-15 18:09 UTC, Mercunus commented
> > можете рассказать, почему работа оценена 2 баллами?
> 
> Да, без проблем
> 
> 1. Непредвиденные ошибки синтеза, в том числе критические. Если вы их видите -- дизайн точно не стоит отправлять на ревью
> 2. Вы не поняли задание в первый раз -- это нормально, так как мы описали его так, что возможны разночтения. Но если вторая и третья проверка выявила ту же ошибку, то это уже минус.
> 3. Исправления, которые могли бы быть проверены симуляцией разных положений key[0] и key[2] перед отправкой. На мой взгляд описанные тесткейсы можно предусмотреть в тестбенче.
> 4. Использование неблокирующих присваиваний в блоке комбинационной логики. На странице о верилоге в вики об этом говорится, это значительная ошибка. Как и присваивание в один регистр в разных блоках always.
> 5. Кодстайл и мелкие недочеты почти не учитывались. В следующих лабах на них больше будет обращаться внимания.
> 6. Оценивалась в основном индивидуальная часть по понятным, думаю, причинам. Основная часть значима только если вы повторяете недочеты из нее, у вас их почти не было и они касались кодстайла.
> 
> Первые 4 пункта мной оценивались _примерно_ как -1, но 2 балла из 5 уже достаточно мало, плюс основная часть у вас была неплохая
> Надеюсь ответила на вопрос

Да, спасибо