Lab2 Индивидуальное задание
HepoH3/MIET_FPGA_practicum pull request #84
Opened 2020-05-13 08:27 UTC by Che100r

# Публикуя данный пул-реквест, я гарантирую, что:
1) Я предлагаю к слиянию только файлы с hdl-описанием разрабатываемого вами устройства, а так же тестбенчи для его тестирования. Исключением могут разве что быть (но не обязаны) файлы .gitignore, и файлы констрейнов (.xdc), tcl-скрипты для сборки проекта.
2) Мной не были удалены исходные файлы репозитория;
3) Мной реализовано устройство в соответствии с данным в исходном репозитории прототипом. Таким образом, любой человек, зная исходный файл репозитория сможет подключить моё устройство к своему проекту и все соберётся.
4) Мой код соответствует [кодстайлу](http://82.179.184.185:82/doku.php?id=verilog_guideline);
5) Коммиты в публикуемом мной пулл-реквесте являются [содержательными](https://habr.com/ru/post/416887/);  
6) Перед отправкой пул-реквеста я убедился, что мой проект собирается, и проведя собственные тесты оказался удовлетворён его работой.

Задание:
3) По после трех нажатий на key[0] происходит событие.
5) Вместо сложения делать циклический сдвиг счетчика. Начальное значение 8’b0010_1100

2020-05-13 09:06 UTC, DOOMKEKER commented
В мастера пушишь жеж

2020-05-13 09:09 UTC, HepoH3 commented
> 
> 
> В мастера пушишь жеж

Ля, спасибо что обратил внимание!

2020-05-13 09:09 UTC, Che100r commented
Точно, извините. Мне пересоздать?

2020-05-13 09:10 UTC, HepoH3 commented
> 
> 
> Точно, извините. Мне пересоздать?

Не надо, обновил.

2020-05-14 08:34 UTC, HepoH3 requested changes
Кроме замечания ниже, раз уж вы все равно будете еще коммитить, добавьте такую же реакцию и для светодиодов, поскольку они с семисегментниками работают от одного и того же события.

2020-05-14 08:34 UTC, HepoH3 commented on lab2/rtl/counter.v
> +          counter_i = counter_i << 1;
Здесь вы делаете битовый сдвиг, но он не циклический. Если 24 раза нажать кнопку, ваш дизайн гарантированно будет выдавать нули до следующего ресета.

2020-05-14 11:08 UTC, HepoH3 approved these changes
Принято.

2020-05-14 11:08 UTC, merged