Григорьева А. ИВТ-23 Индивидуальное задание ( 8 + 1  ) ЛР №2
HepoH3/MIET_FPGA_practicum pull request #88
Opened 2020-05-13 13:58 UTC by SourMandarin

# Публикуя данный пул-реквест, я гарантирую, что:
1) Я предлагаю к слиянию только файлы с hdl-описанием разрабатываемого вами устройства, а так же тестбенчи для его тестирования. Исключением могут разве что быть (но не обязаны) файлы .gitignore, и файлы констрейнов (.xdc), tcl-скрипты для сборки проекта.
2) Мной не были удалены исходные файлы репозитория;
3) Мной реализовано устройство в соответствии с данным в исходном репозитории прототипом. Таким образом, любой человек, зная исходный файл репозитория сможет подключить моё устройство к своему проекту и все соберётся.
4) Мой код соответствует [кодстайлу](http://82.179.184.185:82/doku.php?id=verilog_guideline);
5) Коммиты в публикуемом мной пулл-реквесте являются [содержательными](https://habr.com/ru/post/416887/);  
6) Перед отправкой пул-реквеста я убедился, что мой проект собирается, и проведя собственные тесты оказался удовлетворён его работой.

2020-05-13 14:01 UTC, SourMandarin commented
![Вариант](https://user-images.githubusercontent.com/51454241/81821855-0fdd6c80-953b-11ea-86fc-797ea0b9fa5f.png)
### **Блок 1**
![б1](https://user-images.githubusercontent.com/51454241/81821981-3a2f2a00-953b-11ea-963e-3ea7c885b9d7.png)
### **Блок 2**
![б2](https://user-images.githubusercontent.com/51454241/81822065-53d07180-953b-11ea-9ac3-767b31ca7e56.png)

2020-05-14 14:35 UTC, frarrr requested changes

2020-05-14 14:35 UTC, frarrr commented on lab2/rtl/counter.v
>  end
Из-за этих строчек у меня после синтеза генерируется 126 критических предупреждений и еще сколько-то обычных. Напишите, если ваша версия vivado ничего не выдает в ответ на них.

Проблемы здесь следующие:
1) В разных блоках always нельзя присваивать значение одним и тем же регистрам. В каком блоке регистры используются, в том -- и сбрасываются.
2) В блоке комбинационной логики у вас используется неблокирующее присваивание.
3) Кажется что в ситуации, когда key0 была нажата и отпущена, а затем была нажата key2, счетчик у вас инкрементируется. Нужно сделать так, чтобы он увеличивался когда обе кнопки нажаты, но последней была нажата key2

2020-05-14 16:19 UTC, frarrr commented on lab2/rtl/counter.v
>  end
Также условие `if ( counter == 8'd255 )` здесь не нужно, так как оно выполнится в любом случае при переполнении

2020-05-14 18:07 UTC, SourMandarin commented
Поправлены ошибки

2020-05-15 10:48 UTC, frarrr requested changes

2020-05-15 10:48 UTC, frarrr commented on lab2/rtl/counter.v
> +      b_event <= 1'd0;
Кажется что эти события не противоречат друг другу, но все же если вы в разных `if` присваиваете значения в один регистр, то я бы рекомендовала писать:
```
if ( ... )
else if ( ... )
else if ( ... )
```
Так вы точно не ошибетесь в том, пересекаются ли условия и могут ли они противоречить друг другу

2020-05-15 10:48 UTC, frarrr commented on lab2/rtl/counter.v
> +integer         counter_int;
`integer` -- это фактически `reg signed [31:0]`. Зачем он вам здесь?

2020-05-15 10:48 UTC, frarrr commented on lab2/rtl/counter.v
> +  .in  ( ( counter_int % 100 ) / 10 ),
Такие условия более понятно и читаемо оформить как `wire`, например

2020-05-15 11:57 UTC, SourMandarin commented on lab2/rtl/counter.v
> +integer         counter_int;
Он нужен мне для разбиения полученного числа счётчика на единицы, десятки и сотни и отправки их на хексы

2020-05-15 12:01 UTC, frarrr commented on lab2/rtl/counter.v
> +integer         counter_int;
Вопрос скорее в том, почему для этого не использовать напрямую `counter`?

2020-05-15 12:12 UTC, SourMandarin commented on lab2/rtl/counter.v
> +integer         counter_int;
Непривычно работать с двоичной системой. Непонятно, можно ли 8-миразрядное двоичное число преобразовать в десятичное и разбить его на единицы, десятки и сотни без лишней мороки и переменных. Поэтому сделала так, чтобы наверняка.

2020-05-15 12:20 UTC, frarrr commented on lab2/rtl/counter.v
> +integer         counter_int;
Просто из-за того, что вы добавили этот сигнал, у вас появился лишний большой регистр, который дополнительно на один такт задерживает значение счетчика. counter может изменяться от 0 до 255, поэтому да, конечно его можно преобразовать
Если вы не уверены в том, как counter ведет себя при делении, взятии остатка и пр., лучше просимулировать его поведение, а не добавлять лишнюю логику

2020-05-15 12:45 UTC, SourMandarin commented on lab2/rtl/counter.v
> +integer         counter_int;
Хорошо, я поняла. Уже исправила код, как Вы указали. Сейчас отправлю.

2020-05-15 12:52 UTC, SourMandarin commented
Работа исправлена

Изменений в работе программы на временной диаграмме нет. Как могу судить по ней, код работает правильно.

При синтезе у меня нет предупреждений.

2020-05-15 13:45 UTC, frarrr commented
Вот ситуация, когда обе кнопки не нажаты одновременно, но счетчик увеличивается
![изображение](https://user-images.githubusercontent.com/24639645/82056933-4f3ac300-96cb-11ea-83d2-d1fde21d0bf4.png)

2020-05-15 14:51 UTC, SourMandarin commented
Работа исправлена

Теперь счётчик считает только если зажата кнопка key[0] и нажата кнопка key[2] 
При повторном нажатии на key[2], если key[0] не была отпущена, счётчик не сработает.
Как и не сработает при одновременном нажатии кнопки.

![изображение](https://user-images.githubusercontent.com/51454241/82063863-b1e48c80-96d4-11ea-9c79-e5a563cabae0.png)

2020-05-15 15:09 UTC, frarrr commented
Теперь возникает похожая ситуация:

![изображение](https://user-images.githubusercontent.com/24639645/82065477-d04b8780-96d6-11ea-979c-2dbc5c0596d0.png)

Для предыдущего случая все же тоже засчиталось одно нажатие:

![изображение](https://user-images.githubusercontent.com/24639645/82065690-1bfe3100-96d7-11ea-9ce4-283b66065233.png)

2020-05-15 15:24 UTC, frarrr commented on lab2/rtl/counter.v
> +reg              b_event     = 1'd1;
Здесь не стоит записывать начальное значение в регистр при его объявлении. Не всеми САПР эта операция корректно воспринимается при синтезе и не во всех устройствах она будет работать. У вас уже присвоено начальное значение `b_event` в ресете, этого достаточно

2020-05-15 15:32 UTC, SourMandarin commented
У меня на симуляции счётчик не считает в этих случаях

![1](https://user-images.githubusercontent.com/51454241/82068142-4d2c3080-96da-11ea-862b-d31987c709db.png)

![2](https://user-images.githubusercontent.com/51454241/82068149-4f8e8a80-96da-11ea-86e0-4ff6eff41183.png)

2020-05-15 15:49 UTC, frarrr commented
Разница скорее всего в том, что у меня в тесте кнопки переключаются на отрицательном фронте сигнала + в первом примере важна длительность сигнала (поэтому на времянке есть clk)

2020-05-15 15:52 UTC, frarrr commented
Возможно в таком сценарии поймаете ошибку:

![изображение](https://user-images.githubusercontent.com/24639645/82070308-39ce9480-96dd-11ea-96b3-a350ffc16895.png)

2020-05-15 16:09 UTC, SourMandarin commented
У меня clk100_i начинает считать с 1, у Вас с 0. Как правильно?

2020-05-15 16:12 UTC, frarrr commented
clk может с любого значения начинаться, не принципиально
С кнопками скорее логика в том, что они асинхронны относительно модуля, то есть значение на входе может появиться в любой момент безотносительно clk.

2020-05-15 16:56 UTC, SourMandarin commented
Как я поняла, проблема в асинхронности кнопок. И флаг зажатия key[0] срабатывает, если оно асинхронно с тактом, поэтому срабатывает счётчик, ибо в этом же такте нажимается key[2]. 
Боюсь, что исправить я это не могу. Да и смысла не вижу, ибо задание переделывалось уже много раз.

Тем более, я так и не поняла, где в условии обозначено, что key[0] вообще должна быть зажата во время нажатия на key[2]. Там сообщено лишь об очерёдности.

2020-05-15 17:18 UTC, frarrr commented
> Боюсь, что исправить я это не могу. Да и смысла не вижу, ибо задание переделывалось уже много раз.

Возможно позже придумаете решение. Даже если задание переделывалось, некоторое количество баллов за выполненную лабу получить можно

> Тем более, я так и не поняла, где в условии обозначено, что key[0] вообще должна быть зажата во время нажатия на key[2]. Там сообщено лишь об очерёдности.

Оно не обозначено, это наш недочет. Его первоначальная неверная интерпретация поэтому за ошибку не считается

2020-05-16 15:14 UTC, HepoH3 approved these changes
Здравствуйте.  Дарья пока не может проверить ваши коммиты, поэтому дальнейшую приёмку буду вести я. По дизайну в целом все хорошо, по коду мелкие замечания вы можете увидеть ниже. Они не требуются прямо сейчас к исправлению, просто обратите на них внимание и не допускайте подобных ошибок в следующих лабораторных работах.

2020-05-16 15:14 UTC, HepoH3 commented on lab2/tb/counter_tb.v
>  //////////////////////////////////////////////////////////////////////////////////
В ревью дальше не дотягиваюсь, но там автоматически сгенерированная шапка от вивадо. В следующих лабах давайте вы будете ее удалять, она не несет никакой полезной нагрузки. Тем более, что вы ее не заполняете там под свои проекты.

2020-05-16 15:14 UTC, HepoH3 commented on lab2/rtl/counter.v
> +//  );
Это называется "мёртвый код" и не приветствуется в более-менее нормальных проектах. Он никуда не потеряется, поскольку остался в истории коммитов, только засоряет текущую ревизию кода и является бомбой замедленного действия, если кто-то случайно раскомментирует его.

2020-05-16 15:14 UTC, HepoH3 commented on lab2/tb/counter_tb.v
> +  #100 sw[2] = 1'b1;
Вот это совсем нездоровая штука. Почитайте про блок `repeat`.

2020-05-16 15:18 UTC, HepoH3 commented on lab2/tb/counter_tb.v
> +  #100 sw[2] = 1'b1;
Помимо прочего, нами осуждаются коммиты вида:
```
Правки
Ещё правки
Больше правок Богу Правок
```
В дальнейшем может дойти до того, что лично я могу начать и баллы начать срезать, если не увижу иных мотивационных рычагов для нормальных сообщений к коммитам.

2020-05-16 15:20 UTC, merged